### ISSUE TITLE
setup.py not found

### ISSUE THREAD

**Issue by rajsodhi** [viblo/pymunk#104]
Instructions say:
Compiled libraries of Chipmunk compatible Windows and Linux 32bit and 64bit 
        are distributed with pymunk.
        If pymunk doesnt have your particular platform included, you can compile 
        Chipmunk by hand with a custom setup argument::

```
        > python setup.py build_chipmunk
```

unfortunately, setup.py was not included in .zip file or .whl file.

How do we get around this problem?

Yours,

Raj

**Comment by rajsodhi** [comment]
In this GitHub, I found setup.py, though it was not available at the pymunk website.
When I tried running the chipmunk install command, I had problems...
E:\Users\raj_s\Documents\Python\pymunk-master>python setup.py build_ext --inplace
running build_ext
Running on Windows. GCC will be forced used
Traceback (most recent call last):
  File "setup.py", line 200, in <module>
    ext_modules = extensions,
  File "C:\Python35\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Python35\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Python35\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 48, in run
    self.compiler = cc.new_compiler(compiler=self.compiler)
  File "C:\Python35\lib\distutils\ccompiler.py", line 1031, in new_compiler
    return klass(None, dry_run, force)
  File "C:\Python35\lib\distutils\cygwinccompiler.py", line 282, in __init__
    CygwinCCompiler.__init__ (self, verbose, dry_run, force)
  File "C:\Python35\lib\distutils\cygwinccompiler.py", line 126, in __init__
    if self.ld_version >= "2.10.90":
TypeError: unorderable types: NoneType() >= str()

E:\Users\raj_s\Documents\Python\pymunk-master>


thoughts?

Yours,

Raj

**Comment by viblo** [comment]
Seems like there is some confusion here. 

1. Can you tell me which .zip you downloaded? The one hosted on pypi, https://pypi.python.org/pypi/pymunk have everything included, including setup.py?
2. From your error message it seems you run Windows. Then the chipmunk dll is already included in the wheel (whl) file (what you get if you do `pip install` for example). You dont need to compile it by yourself if you use the wheel on Windows.

**Comment by rajsodhi** [comment]
I originally downloaded this from:
[https://github.com/estevaofon/angry-birds-python](url)
and that's where I noticed I was unable to follow the instructions, because the setup.py didn't exist in that package.  

Using [https://github.com/viblo/pymunk](url) I was able to find a setup.py, and instead of doing 
`python setup.py build_ext`
as per the instructions, I had better luck with 
`python setup.py build_py`
Lots of 'I copied this here' messages and no error messages...

But the main.py program from the angry birds continues to fail with the following message:
```
RESTART: E:\Users\raj_s\Documents\Python\angry-birds-python-master\src\main.py 
Loading chipmunk for Windows (64bit) [E:\Users\raj_s\Documents\Python\angry-birds-python-master\src\pymunk\chipmunk64.dll]

Failed to load pymunk library.

This error usually means that you don't have a compiled version of chipmunk in 
the correct spot where pymunk can find it. pymunk does not include precompiled 
chipmunk library files for all platforms. 

The good news is that it is usually enough (at least on *nix and OS X) to 
simply run the compile command first before installing and then retry again:

You compile chipmunk with
> python setup.py build_chipmunk
and then continue as usual with 
> python setup.py install
> cd examples
> python basic_test.py

(for complete instructions please see the readme file)

If it still doesnt work, please report as a bug on the issue tracker at 
http://code.google.com/p/pymunk/issues
Remember to include information about your OS, which version of python you use 
and the version of pymunk you tried to run. A description of what you did to 
trigger the error is also good. Please include the exception traceback if any 
(usually found below this message).

Traceback (most recent call last):
  File "E:\Users\raj_s\Documents\Python\angry-birds-python-master\src\main.py", line 8, in <module>
    import pymunk as pm
  File "E:\Users\raj_s\Documents\Python\angry-birds-python-master\src\pymunk\__init__.py", line 58, in <module>
    from . import _chipmunk as cp
  File "E:\Users\raj_s\Documents\Python\angry-birds-python-master\src\pymunk\_chipmunk.py", line 13, in <module>
    chipmunk_lib = load_library("chipmunk", debug_lib=_lib_debug)
  File "E:\Users\raj_s\Documents\Python\angry-birds-python-master\src\pymunk\libload.py", line 68, in load_library
    lib = platform_specific_functions()['library_loader'].LoadLibrary(libfn)
  File "C:\Python35\lib\ctypes\__init__.py", line 425, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python35\lib\ctypes\__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
>>> 
```

Since the setup.py ran in a separate directory, I think I might need to copy the pymunk build directory from:
E:\Users\raj_s\Documents\Python\pymunk-master\build\lib.win-amd64-3.5\pymunk
to:
E:\Users\raj_s\Documents\Python\angry-birds-python-master\src\pymunk

but E:\Users\raj_s\Documents\Python\pymunk-master\build\lib.win-amd64-3.5\pymunk
doesn't contain the chipmunk.dll file.  
Would that matter?

Yours,

Raj

**Comment by viblo** [comment]
Right, now I know the problem. The Angry Birds Python project uses Pymunk 4.0. That version doesnt support 64 bit Python on Windows (64 bit Python on Linux and OSX works). From your error log it seems like you are using 64 bit Python on Windows.

There is no easy fix for this. Pymunk 5.0 and newer does support 64bit Python on Windows, but unfortunately there is some breaking API changes, so the game probably needs updating to be able to use Pymunk 5+.

(If you were running a 32 bit Python instead the game would start directly, without any compilation required.)

**Comment by viblo** [comment]
I will close this issue since it wont be fixed, and there is a working workaround (use 32bit python)

**Comment by rajsodhi** [comment]
Thanks Viktor.
After a bit of hacking I was able to get the game to play.

Eventually I can try the 32-bit Python as per your suggestion.
