### ISSUE TITLE
AttributeError: module 'pymunk' has no attribute 'pygame_util'

### ISSUE THREAD

**Issue by rajsodhi** [viblo/pymunk#107]
`import pygame`
`from pygame.locals import *`
`from pygame.color import *`
`import pymunk`
`pygame.init()`
`screen = pygame.display.set_mode((600, 600))`
`clock = pygame.time.Clock()`
`running = True`
`space = pymunk.Space()`
`space.gravity = (0.0, -100.0)`
`draw_options = pymunk.pygame_util.DrawOptions(screen)`

==============================
and here I get an error:

runfile('E:/Users/raj_s/Documents/Python/learn_python/HelloWorldPymunk.py', wdir='E:/Users/raj_s/Documents/Python/learn_python')
Loading chipmunk for Windows (32bit) [C:\Program Files (x86)\Anaconda3\lib\site-packages\pymunk\chipmunk.dll]
Traceback (most recent call last):

  File "<ipython-input-1-00dd3b576384>", line 1, in <module>
    runfile('E:/Users/raj_s/Documents/Python/learn_python/HelloWorldPymunk.py', wdir='E:/Users/raj_s/Documents/Python/learn_python')

  File "C:\Program Files (x86)\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "C:\Program Files (x86)\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "E:/Users/raj_s/Documents/Python/learn_python/HelloWorldPymunk.py", line 21, in <module>
    draw_options = pymunk.pygame_util.DrawOptions(screen)

AttributeError: module 'pymunk' has no attribute 'pygame_util'
=====================================

I tried upgrading pymunk, but it was already up to date.
I'm stumped!

Yours,

Raj

**Comment by viblo** [comment]
A couple of questions:

1. What version of pymunk do you use?
2. How did you install pymunk?
3. Except for pymunk.pygame_util it works? If you remove the last line, does it work then?

**Comment by ericloong90** [comment]
Having the same issue, pymunk has no attribute pygame_util. 
Using pymunk@5.1.0. Installed pymunk via pip.

**Comment by viblo** [comment]
Looking at this again I see your problem. The submodules of pymunk are not imported automatically, so you need to import them yourself (just like it works with the pygame submodules). Try this:
```
import pymunk.pygame_util
options = pymunk.pygame_util.DrawOptions(screen)
```
or
```
from pymunk.pygame_util import DrawOptions
options = DrawOptions(screen)
```

**Comment by ericloong90** [comment]
Yup that solved the issue for now. Just added another line to minimise changes onto preexisting code. Thanks for the reply! 

```python
import pymunk.pygame._util
```

**Comment by viblo** [comment]
I have updated the docs with an example for pgame_util so it should be more clear how to do it now.
