### ISSUE TITLE
Misleading bit about dynamic body construction in documentation

### ISSUE THREAD

**Issue by Normangorman** [viblo/pymunk#108]
The documentation [here](http://www.pymunk.org/en/latest/pymunk.html#pymunk.Body.__init__) says:

> There are two ways to set up a dynamic body. The easiest option is to create a body with a mass and moment of 0, and set the mass or density of each collision shape added to the body. Chipmunk will automatically calculate the mass, moment of inertia, and center of gravity for you. This is probably preferred in most cases.

However pymunk does not allow creation of dynamic bodies with 0 mass/moment:
Attempting this:

`body = pymunk.Body(mass=0, moment=0, body_type=pymunk.Body.DYNAMIC)`

Results in:

`AssertionError: dynamic body with 0 mass and/or moment`

I think this bit in the documentation should be changed as it's misleading.

**Comment by viblo** [comment]
Thanks for the report.

Maybe it would be better to actually implement what the docs say, seems like its a new feature in Chipmunk that was missed when Pymunk 5 was released. I will check if its easy to do and if so implement it, otherwise update the docs to reflect whats implemented.

**Comment by viblo** [comment]
Now I fixed the implementation to follow the docs, so that its possible to set the mass/moment on a shape and let Pymunk calculate the total mass/moment/center of gravity of the body based on the shapes attached to it.
