### ISSUE TITLE
pyglet_util debug draw incorrectly renders polygons with more than 5 sides

### ISSUE THREAD

**Issue by Normangorman** [viblo/pymunk#109]
Here is an example of the bug when trying to render a septagon:

![pyglet_debug_draw_7gon](https://cloud.githubusercontent.com/assets/6610341/23549751/95ec3172-0005-11e7-9d49-3626f6e6e4fd.PNG)

To produce this I have modified part of `examples/shapes_for_draw_demos.py`. I have changed line 60 to:

```python
s = pymunk.Poly(b, [(0.0, -30.0), (19.0, -23.0), (30.0, -5.0), (26.0, 15.0), (10.0, 28.0), (-10.0, 28.0), (-26.0, 15.0), (-30.0, -5.0), (-19.0, -23.0)], t)
```

The bug seems to happen for any equilateral shape with more than 5 sides. Here is an example with a 9-gon:
![9gon](https://cloud.githubusercontent.com/assets/6610341/23549991/a9e5a7de-0006-11e7-9ad6-acffb0c4f9d5.PNG)

I think this may be caused by the way that GL_TRIANGLE_STRIP is being used in this method in `pyglet_util.py`:

```python
 def draw_polygon(self, verts, radius, outline_color, fill_color):
        ps = verts
            
        mode = pyglet.gl.GL_TRIANGLE_STRIP
        ps = [ps[1],ps[2], ps[0]] + ps[3:]
        
        vs = []
        for p in [ps[0]] + ps + [ps[-1]]:
                vs += [p.x, p.y]
            
        l = len(vs)//2
        self.batch.add(l, mode, None,
                    ('v2f', vs),
                    ('c4B', fill_color.as_int()*l))
```

I may try and submit a fix for this, although I don't have great knowledge of OpenGL

**Comment by viblo** [comment]
Thanks for the report. I have committed a fix (and test case to show it), feel free to test it at latest master

**Comment by Normangorman** [comment]
Great! Impressive response time 👍
