### ISSUE TITLE
Collisions with Static Segments

### ISSUE THREAD

**Issue by alexbaikovitz** [viblo/pymunk#111]
Collisions with a static segment seem to be causing circles to simply roll on the segment rather than deflect off them, even with high elasticity. How can instances of deflection off walls (Segments or the equivalent) be made?

**Comment by viblo** [comment]
Can you provide an example to recreate the problem? The bouncing_balls.py example (https://github.com/viblo/pymunk/blob/master/examples/bouncing_balls.py) shows bouncing balls on static segments.

**Comment by viblo** [comment]
Im closing this since it seems liek its not a problem. Feel free to post some example code if it is indeed still an issue and I will reopen.
