### ISSUE TITLE
Nested BB.merge() calls raise TypeError

### ISSUE THREAD

**Issue by jackamander** [viblo/pymunk#112]
With 5.2.0 on Python 2.7.13, the following fails for me:
import pymunk
bb = pymunk.BB()
bb.merge(bb.merge(bb))

Traceback (most recent call last):
  File "<pyshell#10>", line 1, in <module>
    bb.merge(bb.merge(bb))
  File "C:\Python27\lib\site-packages\pymunk\bb.py", line 72, in merge
    return BB(lib._cpBBMerge(self._bb[0], other._bb[0]))
TypeError: cdata of type 'cpBB' cannot be indexed

The exception occurs in the second call to merge.  It looks like any BB object returned by BB.merge() doesn't function exactly like a "normal" BB object.

**Comment by viblo** [comment]
Thanks for the report. It should be fixed in latest commit.
