### ISSUE TITLE
Copy method for `Space' object?

### ISSUE THREAD

**Issue by Rick-C-137** [viblo/pymunk#114]
In my code, I often find I want to run different simulations in parallel under different conditions, or run a simulation forward, but easily revert back to the initial conditions. So I need to make independent copies of the space. It would be very convenient to have a copy method, because otherwise I need to manually re-extract all the coordinates of all the bodies, etc., or keep passing around the parameters used to make the original. I've tried making copies with Pickle, cPickle, and JSON, and none of these works.

**Comment by viblo** [comment]
Thanks for the report! Yeah, currently there is no built in functionality for copy or serializing/deserializing pymunk objects. However, it is something I have thought about adding. 

There are some parts that are troublesome, for example some state is kept internally to make collision resolving faster and more stable, and then there is the issue of the collision callbacks, if you copy a space with two shapes that have started colliding and triggered the begin collision handler, should it be called again the copy?

But maybe this feature would be useuful even if the above is not handled perfectly.

**Comment by viblo** [comment]
Thanks for the report! Yeah, currently there is no built in functionality for copy or serializing/deserializing pymunk objects. However, it is something I can see being useful for many cool things. 

There are some parts that are troublesome, for example some state is kept internally to make collision resolving faster and more stable. Without it everything will be a bit unstable the first couple of simulation steps until the internal state cache has been filled. Then there is also the issue of the collision callbacks, if you copy a space with two shapes that have started colliding and triggered the begin collision handler, should it be called again the copy?

But maybe this feature would be useful even if the above is not handled perfectly.. I will do some experiments to test it out.

**Comment by viblo** [comment]
I have added pickle support for shapes, bodies, constraints and spaces during the last couple of days (master branch). It seems to work fine in the limited tests Ive done so far. Following this my plan is to make an example using pickle, update the documents and test if copy.deepcopy work. Then if everything seems stable and works fine I think I will do a release, 5.3.0.

If you are interested feel free to try out the latest master branch. 
(unless I hear anything else I will close this issue once Im confident the pickle support works properly)

**Comment by Rick-C-137** [comment]
Thanks. I'll be likely to use that in the future. 

Are you holding off on including the copy method in the Space object itself because you don't want to import additional packages? Would definitely be nice to just be able to do `myspace.copy()`, like you can do with numpy arrays.

**Comment by viblo** [comment]
I haven't put too much thought about it yet. Since there is a copy library (with deepcopy function) included in the standard lib python I thought maybe it would be enough. On the other hand, having a copy function directly on the space makes it a bit easier to discover and use.

Implementation wise its no trouble, it would just be `import copy; return copy.deepcopy(self)`), so its only a matter of API cleanliness.

Looking around it seems like in addition to numpy arrays also the common python dict object have a dedicated copy function.. If I go with a dedicated copy function, do you think just the space needs it, or also the other objects (Body, Poly, Segment, Circle and the constraints)?

**Comment by Rick-C-137** [comment]
I think also having copy methods for Body, Poly, etc. is a good idea. I haven't personally needed them yet, that I can remember, but I could imagine them being useful.

**Comment by viblo** [comment]
In the end I decided to add a copy method. So now Space, Body and the others both support pickle and the std lib copy, but also have a dedicated copy method so you can do `myspacecopy = myspace.copy()`. (Available in latest master branch, will be included in next release of pymunk).
