### ISSUE TITLE
Update docs for Segment

### ISSUE THREAD

**Issue by Rick-C-137** [viblo/pymunk#115]
In Pymunk 5.2.0 (on OS X 10.10.5 and Pygame 1.9.3), if I try to add a static Segment to the space by passing `None` as the body argument, 
`ground = pymunk.Segment(None, (x0, y0), (x1, y1), thickness)`
I get a pygame segmentation fault. But I looked in the box2d_pyramid example, which instead passes in `space.static_body`, which works on my system. If the error is not specific to my system, then maybe update the docs?

**Comment by viblo** [comment]
Thanks for the report! It is legal to create a Shape without a body, but before you add it to the space you must set it. I can see that its not very clear so I updated the docs.
