### ISSUE TITLE
Get vertices of a Polygon 

### ISSUE THREAD

**Issue by Somtha** [viblo/pymunk#117]
Is there a way to obtain a new set of vertices for a Polygon after it has moved (Like in Pymunk 4.0.0)? Using "get_vertices()" only returns the vertices that were defined in the creating of the shape.

I'm looking to use the vertices to draw a Pygame rect directly over the Pymunk Poly.

**Comment by cprogrammer1994** [comment]
if you can get the position and rotation of the object is is just simple math to get the transformed vertices.

**Comment by viblo** [comment]
You can use this way:
`transformed_vertices = [p.rotated(myshape.body.angle) + myshape.body.position for p in myshape.get_vertices()]`

Some of the examples does their drawing like this, for example the pygame sprite example: https://github.com/viblo/pymunk/blob/master/examples/using_sprites.py#L98
