### ISSUE TITLE
No module named 'pygame'

### ISSUE THREAD

**Issue by sasalicat** [viblo/pymunk#123]
when I execute arrow.py 
It give me this problem,and I search your file 
there is not such file named pygame ,so what is that?how can I fix this problem?

**Comment by viblo** [comment]
Pygame is a python multimedia library that can be used for example for game programming. Do you have pygame installed? If not you need to install it to be able to run the examples that use pygame (which is most of them). 

https://www.pygame.org/wiki/GettingStarted#Pygame%20Installation

Note that some examples require other libraries (pyglet and matplotlib with jupyter notebook)

**Comment by cprogrammer1994** [comment]
```
pip install pygame
```
