### ISSUE TITLE
can I make a object trigger collision events without physical collision?

### ISSUE THREAD

**Issue by sasalicat** [viblo/pymunk#124]
like the trigger mode of Unity`s collision
let me show a example the Powershot of wind Runner in dota
is a arrow can through roles but no physical collision as it won`t push the role 
I really want to know the way

if that`s no way,I think I would use point_query every frame
so it`s a big cost that do it every frame for every missile?
or your collision system just do  what I said to determine if collisions happen?

I will appreciate if you answer my question
by the way do pymunk have a online forum?

**Comment by viblo** [comment]
Yes, its possible to skip the collision response. 
Either you can set the sensor property on the shape to True. http://www.pymunk.org/en/latest/pymunk.html#pymunk.Shape.sensor 
Or you can use a custom collision handler and return False in the begin handler: http://www.pymunk.org/en/latest/pymunk.html#pymunk.CollisionHandler.begin which is a bit more flexible but a little more complex.

Pymunk does not have its own forum. For clear questions/answers I think the best is to ask on stackoverflow.com with the pymunk tag https://stackoverflow.com/questions/tagged/pymunk
If you want a more general discussion either here on github or in the chipmunk forum (pymunk is built on top of chipmunk so many things are the same): http://chipmunk-physics.net/forum/index.php
