### ISSUE TITLE
How to check two circles or rectangles are crashed?

### ISSUE THREAD

**Issue by deepmeng** [viblo/pymunk#130]
Hello, I am a new learner.  I define a rectangle which means a car in my scene and some circles and lines   to represent obstacles. I'm just want to know how to check my car is crashed with any other shapes?  Is there a function to check it and return a result of True or False ???

**Comment by Berserker66** [comment]
You attach a collisionhandler that gets called back when the collision occurs:
http://www.pymunk.org/en/latest/pymunk.html#pymunk.CollisionHandler

**Comment by deepmeng** [comment]
@Berserker66  Thank you very much!  It's already solved.
