### ISSUE TITLE
How to draw a hollow circle?

### ISSUE THREAD

**Issue by deepmeng** [viblo/pymunk#131]
I can't find any interfaces to draw a hollow circle?

**Comment by viblo** [comment]
What do you mean by "draw"? 

Pymunk does not have built in support for hollow circle shapes. You can calculate the moment and area correctly with `moment_for_circle` and `area_for_circle`, but the circle wont be hollow, only behave as if it was hollow. If you want an actual hole in the circle you need to build it yourself, for example with a bunch of segment shapes all attached to the same body.

**Comment by deepmeng** [comment]
I want to define two concentric circles and define a box to run between them. Do you have any ideas?

**Comment by viblo** [comment]
It sounds like the easiest would be to approximate outer circle with a bunch of segments.
