### ISSUE TITLE
ImportError: cannot import name 'Vec2d'

### ISSUE THREAD

**Issue by thedigitalempress** [viblo/pymunk#133]
I'm writing a simple python game instructed by raspberry pi. Unfortunately, on my pi and MacBook I get this error when I run the code:

**ImportError: cannot import name 'Vec2d'**

The program is supposed to have a triangle with floating balls. 
![screen shot 2017-11-23 at 2 53 21 am](https://user-images.githubusercontent.com/33044102/33162834-94fa7a70-cff9-11e7-8975-550f91d5aa4e.png)
![screen shot 2017-11-23 at 2 53 33 am](https://user-images.githubusercontent.com/33044102/33162837-98c22bb2-cff9-11e7-8824-5dd2e4419ae6.png)
![screen shot 2017-11-23 at 2 53 39 am](https://user-images.githubusercontent.com/33044102/33162840-9ba7465a-cff9-11e7-99e9-939066d14066.png)
![screen shot 2017-11-23 at 2 53 48 am](https://user-images.githubusercontent.com/33044102/33162842-9eb37fc6-cff9-11e7-87f6-33b61329e378.png)

**Comment by viblo** [comment]
Try importing Vec2d from the pymunk vec2d submodule instead of importing it from pygame.
Replace `from pygame import Vec2d` with this `from pymunk.vec2d import Vec2d`.

**Comment by thedigitalempress** [comment]
So I tried that and that just made it worse. Here's what the stack trace threw back out at me. I also get this pycache folder in the location where the program is being held after running it.
![screen shot 2017-11-28 at 4 37 37 pm](https://user-images.githubusercontent.com/33044102/33345680-2999d59e-d45b-11e7-81e9-217b27c1b330.png)
![screen shot 2017-11-28 at 4 38 14 pm](https://user-images.githubusercontent.com/33044102/33345682-2c2eeca4-d45b-11e7-886b-e86e7ea1ef08.png)

**Comment by viblo** [comment]
From that exception it seems like pymunk is not installed correctly. 

Can you tell me what Python version, what OS and how/if you installed pymunk and if so which version you used?

**Comment by thedigitalempress** [comment]
Python 3.4.2, Mac OS High Sierra. I did install Pymunk but I honestly think that's my issue. I installed it completely wrong. Do you have any suggestions on installing it correctly on a raspberry pi?

**Comment by thedigitalempress** [comment]
Update: I logged in as root. Deleted anything related to Pymunk from the Python3 folder. Reinstalled it through the terminal using 'sudo pip3 install pymunk'. When I follow the instructions from this site http://www.pymunk.org/en/latest/ it does not build correctly.

**Comment by viblo** [comment]
Do you mean you run python and pymunk on Raspberry Pi or on Mac OS? 

Can you show what errors do you get when you do pip3 install pymunk?

**Comment by thedigitalempress** [comment]
Sorry. So I just re-ran the install of pymunk and now I do not the error. But, I am having trouble with the code pulling up the game properly. 

I also installed "Chipmunk" on both my pi and Mac just in case.

Here is my code. I run the exact same code on my pi and MacBook. 
![screen shot 2017-11-29 at 5 49 09 pm](https://user-images.githubusercontent.com/33044102/33403394-3dc3d956-d52e-11e7-838f-1f3fefb43c0d.png)
![screen shot 2017-11-29 at 5 49 23 pm](https://user-images.githubusercontent.com/33044102/33403397-40209752-d52e-11e7-8e68-8a649bc9802e.png)
![screen shot 2017-11-29 at 5 49 30 pm](https://user-images.githubusercontent.com/33044102/33403400-42d459c0-d52e-11e7-8b20-11f4cfdf7fdc.png)

I get nothing back from the stack trace..
![screen shot 2017-11-29 at 5 49 49 pm](https://user-images.githubusercontent.com/33044102/33403408-4eb6ffa4-d52e-11e7-8a88-aa67e89fcd65.png)

The pygame window opens up blank on both machines.
![screen shot 2017-11-29 at 5 49 55 pm](https://user-images.githubusercontent.com/33044102/33403427-5f3b032a-d52e-11e7-8843-dc1f1b70a3f8.png)

And the I have to click the 'x' button on the Mac pygame window or the python shell on the pi for it to show only this.
![screen shot 2017-11-29 at 5 52 35 pm](https://user-images.githubusercontent.com/33044102/33403476-8defd61e-d52e-11e7-80da-1209801e3f14.png)

It's supposed to look something like this:
![img_8217](https://user-images.githubusercontent.com/33044102/33403847-f23dab54-d52f-11e7-9622-ddc8b286139e.JPG)

**Comment by viblo** [comment]
Ok, some progress! :) 
For your code I cant see a direct problem, but it does seem to load pymunk. 

Could you maybe download and test run this example: https://github.com/viblo/pymunk/blob/master/examples/bouncing_balls.py and see if it works?

Also, if you copy-paste your code here I can try it myself, then its easier to see what is happening. Since you inserted only pictures its difficult for me to test it. :) Either you can copy the code directly here, or even better put it in a gist here https://gist.github.com/ and then put the link here.

**Comment by viblo** [comment]
By the way, it seems like you have a book or magazine with some Pymunk inside. I havent seen it myself, maybe you can tell me which book it is?

**Comment by thedigitalempress** [comment]
Thanks so much!! Here is my code:



import pygame, pymunk
from pygame.locals import *
from pygame.color import *
from pymunk import Vec2d
import math, sys, random

def to_pygame (position):
    return int(position.x), int(-position.y+screen_y)

def line_to_pygame(line):
    body = line.body
    point_1 = body.position + line.a.rotated(body.angle)
    point_2 = body.position + line.b.rotated(body.angle)
    return to_pygame(point_1), to_pygame(point_2)

###option###
screen_x = 600
screen_y = 400
num_balls = 10

pygame.init()
screen = pygame.display.set_mode((screen_x, screen_y))
clock = pygame.time.Clock()
running = True

space = pymunk.Space()
space.gravity = (0.0, -200.0)

#create the base segment
base = pymunk.Segment(pymunk.Body(), (0, 50), (screen_x, 0), 0)
base.elasticity = 0.90
space.add(base)

#create the spinner
spinner_points = [(0, 0), (100, -50), (-100, -50)]
spinner_body = pymunk.Body(100000, 100000)
spinner_body.position = 300, 200
spinner_shape = pymunk.Poly(spinner_body, spinner_points)
spinner_shape.elasticity = 0.5
spinner_joint_body = pymunk.Body()
spinner_joint_body.position = spinner_body.position
joint = pymunk.PinJoint(spinner_body, spinner_joint_body, (0,0), (0,0))
space.add(joint, spinner_body, spinner_shape)

#create the balls
balls = []
for i in range(1, num_balls):
    ball_x = int(screen_x/2)
    radius = random.randint(7, 20)
    inertia = pymunk.moment_for_circle(radius, 0, radius, (0, 0))
    body = pymunk.Body(radius, inertia)
    body.position = ball_x, screen_y
    shape = pymunk.Circle(body, radius, (0,0))
    shape.elasticity = 0.99
    space.add(body, shape)
    balls.append(shape)

while running:
    for event in pygame.event.get():
        if event.type == QUIT:
            running = False
            screen.fill((0, 0, 0))
#draw the ball
    for ball in balls:
        pygame.draw.circle(screen,(100, 100, 100), to_pygame(ball.body.position), int(ball.radius), 0)

#draw the spinner
    points = spinner_shape.get_vertices()
    points.append(points[0])
    pygame_points = []
    for point in points:
        x,y = to_pygame(point)
        pygame_points.append((x, y))
    color = THECOLORS["red"]
    pygame.draw.lines(screen, color, False, pygame_points)

#draw the line
    pygame.draw.lines(screen, THECOLORS["lightgray"], False, line_to_pygame(base))

#space.step(1,0/50,0)
pygame.display.flip()
clock.tick(50)

**Comment by thedigitalempress** [comment]
Also, your program worked!!

![screen shot 2017-11-29 at 7 06 59 pm](https://user-images.githubusercontent.com/33044102/33406260-fcdd01e0-d539-11e7-85da-66277f68636e.png)

**Comment by thedigitalempress** [comment]
The book is Learning Python with Raspberry Pi.

**Comment by viblo** [comment]
Ok, great. If the bouncing_balls.py example works it means pymunk is installed correctly and is working :) 

I took a quick look at the book and your code, maybe the example is for an older version of pymunk? Particularly this part looks strange: `spinner_joint_body = pymunk.Body()`. It might work better with `spinner_joint_body = pymunk.Body(body_type=pymunk.KINEMATIC)`. 

(When you paste code here its best if you use the code tags, since otherwise I cant see the white space. See here for an explanation: https://help.github.com/articles/creating-and-highlighting-code-blocks/ )

**Comment by viblo** [comment]
ps. If you havent seen it, there is a bunch of pymunk examples you can play around with here: http://www.pymunk.org/en/latest/examples.html Most of them only requires pygame to run. (Some other require pyglet or other libraries, but you should be able to run the pygame ones at least)

**Comment by viblo** [comment]
I tested the code you pasted and it needed some small modifications to work. Below I have included a modified version that shows something. I updated the spinner_body and shape and the drawing of the spinner.

```
import pygame, pymunk
from pygame.locals import *
from pygame.color import *
from pymunk import Vec2d
import math, sys, random

def to_pygame (position):
    return int(position.x), int(-position.y+screen_y)

def line_to_pygame(line):
    body = line.body
    point_1 = body.position + line.a.rotated(body.angle)
    point_2 = body.position + line.b.rotated(body.angle)
    return to_pygame(point_1), to_pygame(point_2)

###option###
screen_x = 600
screen_y = 400
num_balls = 10

pygame.init()
screen = pygame.display.set_mode((screen_x, screen_y))
clock = pygame.time.Clock()
running = True

space = pymunk.Space()
space.gravity = (0.0, -200.0)

#create the base segment
base = pymunk.Segment(pymunk.Body(), (0, 50), (screen_x, 0), 0)
base.elasticity = 0.90
space.add(base)

#create the spinner
spinner_points = [(0, 0), (100, -50), (-100, -50)]
spinner_body = pymunk.Body(0,0)
spinner_body.position = 300, 200
spinner_shape = pymunk.Poly(spinner_body, spinner_points)
spinner_shape.mass = 100
spinner_shape.elasticity = 0.5
spinner_joint_body = pymunk.Body(body_type=pymunk.Body.KINEMATIC)
spinner_joint_body.position = spinner_body.position
joint = pymunk.PinJoint(spinner_body, spinner_joint_body, (0,0), (0,0))
space.add(joint, spinner_body, spinner_shape)

#create the balls
balls = []
for i in range(1, num_balls):
    ball_x = int(screen_x/2)
    radius = random.randint(7, 20)
    inertia = pymunk.moment_for_circle(radius, 0, radius, (0, 0))
    body = pymunk.Body(radius, inertia)
    body.position = ball_x, screen_y
    shape = pymunk.Circle(body, radius, (0,0))
    shape.elasticity = 0.99
    space.add(body, shape)
    balls.append(shape)

while running:
    for event in pygame.event.get():
        if event.type == QUIT:
            running = False
    screen.fill((0, 0, 0))
    #draw the ball
    for ball in balls:
        pygame.draw.circle(screen,(100, 100, 100), to_pygame(ball.body.position), int(ball.radius), 0)

    #draw the spinner
    points = spinner_shape.get_vertices()

    points.append(points[0])
    pygame_points = []
    for point in points:
        point = point.rotated(spinner_shape.body.angle) + spinner_shape.body.position
        x,y = to_pygame(point)
        pygame_points.append((x, y))
    color = THECOLORS["red"]
    pygame.draw.lines(screen, color, False, pygame_points)

    #draw the line
    pygame.draw.lines(screen, THECOLORS["lightgray"], False, line_to_pygame(base))

    space.step(1.0/50.0)
    pygame.display.flip()
    clock.tick(50)

```

**Comment by thedigitalempress** [comment]
Ahhh! Thank you so much!! I was going to go crazy if I didn't figure out what was going on. I figured a lot of the projects in this book are outdated. In the next chapter I am supposed to making things with the "rpigl" module and I'm already having issues downloading that one properly. I'm going to try to find some updated projects for the rpigl module since the test code they had me run bounced back alot of errors after trying to run it. 

Also thanks for the heads up about creating and highlighting code blocks in discussions. I'll make note of that next time.

**Comment by viblo** [comment]
Good Luck! :)

I will close this issue now since the pymunk part seems solved.
