### ISSUE TITLE
Add tank demo to examples?

### ISSUE THREAD

**Issue by virtuald** [viblo/pymunk#134]
There don't seem to be any top-down physics examples distributed with pymunk... it seems like the Tank demo does this in Chipmunk. Some of the translation isn't particularly straightforward, so it would be great if it was added. :+1: 

https://github.com/slembcke/Chipmunk2D/blob/master/demo/Tank.c

**Comment by viblo** [comment]
Thanks for the suggestion, seems like a good example to have.

**Comment by keke8273** [comment]
This would be very helpful if translated in python

**Comment by viblo** [comment]
Took a bit of time, but I have ported over the tank demo now. Available here: https://github.com/viblo/pymunk/blob/master/examples/tank.py
