### ISSUE TITLE
bugs after switching from version 4.0.0 to 5.3.2

### ISSUE THREAD

**Issue by su-si** [viblo/pymunk#137]
Hi,
I switched to version 5.3.2 to be able to use filled-in moving rectangles. (This works!) But now, there seem to be two new problems that did not occur with pymunk 4.0.0. 

Setting: A movable box (= four segments) and two bouncing balls/squares inside.

The first thing is that _shape.velocity_limit_ doesn't seem to have any effect any more: Directly after calling 
`        a_space.step(dt)`
I find bodies that have velocities of ~1000, while the debugger tells me that its _velocity_limit_ is set to 200.

Second, for version 4.0.0, I could set a handler for collisions between moving wall and bouncing objects, where the collision distance is set to 0, and got 'nice' bouncing behaviour. But now, with the same handler set, the objects dive into the walls (I restrict velocity manually before calling `a_space.step(dt) `here), they even can get through - at least a long, thin rectangle can. 

For the record, for version 4.0.0 the handler setting was: 
```
        self.space.add_collision_handler(CollisionTypes.MOVING_WALLS.value, CollisionTypes.BOUNCERS.value,
                                             pre_solve=my_pre_solve_fun)
```
where 
```
def my_pre_solve_fun(space, arbiter):
        set_ = arbiter.contacts
        if len(set_) > 0:
            segment_shape = arbiter.shapes[0]
            # calculate the collision normal:
            seg_dir = segment_shape.a - segment_shape.b
            normal = seg_dir.perpendicular_normal()
            set_[0]._normal = normal
            set_[0]._distance = 0
        arbiter._contacts = set_
        return True
```

For 5.3.2:
```
        h = self.space.add_collision_handler(CollisionTypes.MOVING_WALLS.value, CollisionTypes.BOUNCERS.value)
        h.pre_solve = my_pre_solve_fun
```

```
def my_pre_solve_fun(arbiter, space, data):
        set_ = arbiter.contact_point_set
        if len(set_.points) > 0:
            segment_shape = arbiter.shapes[0]
            # calculate the collision normal:
            seg_dir = segment_shape.a - segment_shape.b
            normal = seg_dir.perpendicular_normal()
            set_.normal = normal
            set_.points[0].distance = 0
        arbiter._contacts = set_
        return True
```

Are these bugs? Especially the first one seems like it. Or did velocity_limit become obsolete from version 4 to version 5? Then, how is it done now?

**Comment by viblo** [comment]
For your second problem I dont see the issue directly. However, the collision handling algorithm has changed somewhat between 4.x and 5.x. 
Before I look closer, is there some special reason why you use pre_solve instead of setting the elasticity on the shapes?

**Comment by su-si** [comment]
Thanks!  I'll try the velocity_func, that looks like the intended way to do this. If this is in the (chipmunk-)docs, I missed it, sorry!
And for the second one, probably I'm misunderstanding something, but I'm setting all of the elasticities to 1. as well already. Could it be that when setting pre_solve, elasticity is ignored or so?

But I'll have a look at the second problem again. Maybe it's already solved if the velocity is limited properly.

**Comment by su-si** [comment]
The problem seems solved. `velocity_func` does a great job.

It seems the other problem (going through walls that should be too thick to get through) was _caused_ by setting the collision distance to 0 in a pre_solve. And it happened mostly (only?) with rectangular shapes. (Limiting velocity did not solve it, but removing pre_solve did.)

That pre_solve was coming from the code using version 4. I'm not sure whether it was even neccessary there, or just a leftover.

Thanks a lot.

**Comment by viblo** [comment]
Happy to hear your problem is solved 👍
