### ISSUE TITLE
body=pymunk.Body(mass, moment)   make a lot of mistakes....

### ISSUE THREAD

**Issue by zipandrar** [viblo/pymunk#139]
it will cause somethings like cross the static body(floor).... ... or be hit badly by other bodies and cross the ground.... in pymunk5.3.2

but use  shape.density=1  instead of pymunk.Body(mass, moment)  anything will work wonderful....

chipmunk is very great .......

pymunk is very useful but with some very very small bugs.... ....

thank you any developers.... ...

pymunk with chipmunk is really quick enough...

pyglet's draw and for .... is a neckless...

and  a small tip (maybe useful)

           vertexobject=Layer1_tree_Batch.add(2, gl.GL_LINES, None,
                                  ('v2f', (x,y,x2,y2)),
                                  ('c3f', [0.5, 0.6, 0.7]*2)
                                  )  

will make it quick a lot to change  (lots of )sprite's coords...

**Comment by viblo** [comment]
Great that you like it :)

It sounds strange that setting shape.density works good but not setting the mass/moment directly on the body. Are you sure you set the mass and moment to the same values as what density does? Do you have a small code example of this?
Yes, using batches to draw with pyglet is a great tip to improve pyglet performance. The built in draw helper for pyglet can already use batches (pyglet_util.py).

**Comment by zipandrar** [comment]
if pyglet 's version is 1.3.2  you need to delete the test.py  or test.pyc to run anything... so strange....tip from sites....

**Comment by viblo** [comment]
Ok, I made a quick check and I think I know the reason for different behavior is that the ball have different mass. 
So, there are 3 ways to set the mass and moment of an object:
1. Set the mass and moment of a body.
2. Set the density of the shape attached to body.
3. Set the mass of the shape attached to body.

In pymunk.test.py you set the mass to 10 (and moment become 500) on the body. If you instead set density of the circle shape to 1, it means that the total mass becomes `density * the area of the shape` (which is `r^2*pi`). In this case the area is roughly 314, so mass becomes 314 (and the moment 15708).

Setting the mass and moment by the shape is a quite new feature in pymunk, and I havent used it myself, so the docs are a bit limited on how this works. I will try to clarify it a bit.

**Comment by zipandrar** [comment]
many examples are very "simple"... .... it seems that you dont have many time too.....
thanks for your hard work....

**Comment by viblo** [comment]
I updated the docs for the body class to showcase the different ways to set mass and moment. Hopefully that should make it easier to understand. (I will try to update the examples to set the mass on the shape instead of body as well at some future time, since I think its easier than to set it on the body itself)

**Comment by viblo** [comment]
For you comments about draw speed: The pyglet (and pygame and other) draw methods included in pymunk are mostly there for convenience when you prototype things and want something basic quickly, good for debugging. There are definitely room for optimizations that can be made. 

Anyway, thanks for your comments!
