### ISSUE TITLE
a small error in manual of pymunk doc.....

### ISSUE THREAD

**Issue by zipandrar** [viblo/pymunk#140]
shape.filter=pymunk.ShapeFilter(group=3,categories=10)    

it should be like "categories=0b1000"    

pymunk.ShapeFilter(mask=0b100+0b001)))  it will only find the 0b100 and 0b001

pymunk.ShapeFilter(mask=pymunk.ShapeFilter.ALL_MASKS^0b001^0b1100) #anything without 0b001 and 0b1100

categories=10 make me very hard to get it out... take some hours to get it out ...i am only a python programer,,, without any c or c++ binary operation... ....

maybe change it in manual doc......is best...

**Comment by viblo** [comment]
Thanks for the report! 
Exactly where in the documentation did you see this?

**Comment by zipandrar** [comment]
http://www.pymunk.org/en/latest/pymunk.html#pymunk.ShapeFilter


Object | Object Category | Category Mask
-- | -- | --
Player | 1 | 4, 5
Enemy | 2 | 2, 3, 4
Player Bullet | 3 | 1, 5
Enemy Bullet | 4 | 2, 5
Walls | 5 | 1, 2, 3, 4


Category 1 2 3 4 5

**Comment by viblo** [comment]
Thanks. I committed a clarification, hope it is more clear now.

**Comment by zipandrar** [comment]
passthrough.filter = pymunk.ShapeFilter(categories=0b1000)   (but it is right in examples)

thank you for your wonderful examples....
