### ISSUE TITLE
Getting force during collision

### ISSUE THREAD

**Issue by adammj** [viblo/pymunk#141]
I have a working model in pymunk that has objects that occasionally push against each other. The collision callbacks are working, and I can retrieve the properties of the arbiters. However, arbiter.total_impulse, and body.force are always zero, and arbiter.total_ke isn't quite right.

I know the total_ke isn't working correctly, because two of the bodies are constrained by SlideJoints, and when the joint hits its maximum limit, there should no longer be any force between the two bodies that are in contact. Instead, I see the total_ke drop to a faction of the previous value, but not close to zero.

Short of adding additional bodies connected by springs to the front of the main bodies of interest, how can I go about actually getting a correct representation of the force between two colliding bodies?

**Comment by viblo** [comment]
Which collision handler do you use? The values are only available in the post solve and each_arbiter callbacks.

**Comment by adamjones1** [comment]
I'm attempting to get the values while in the post_solve callback (per the documentation).

**Comment by viblo** [comment]
Ok. Is it possible for you to show some code that shows the problem? That would help a lot to understand were the problem lies. 

Another idea is that you make a small callback for Body.each_arbiter http://www.pymunk.org/en/latest/pymunk.html#pymunk.Body.each_arbiter and add a call to it every frame on one of your objects that you know will collide. Just to see if its exactly 0 all the time.

**Comment by adamjones1** [comment]
I don't think I can easily extract the relevant pieces, so I just uploaded an entire notebook that has the current code (which I'll erase afterwards)
http://online2.mm.st/oropod_pymunk-oo.ipynb
The final plot shows the total_impulse and total_ke

So, I've added a function for each_arbiter, and I can now see that total_impulse is not zero. However, it's just a scaled version of total_ke. The values are still not correct, as there should be zero force between the two colliding bodies once the slidejoint constraint reaches its maximum extent. What I see drawn in pygame looks right: when the constraint hits the end point, the little object (arm) stops pushing the large object (body) away from the wall. However, the arbiter values still reflect a significant impulse and kinetic energy in the collision between the wall and arm.

**Comment by viblo** [comment]
I will try to do some tests and see if I can understand the issue. 

In case you are curios (and can read c code), the actual calculation for total impulse and ke is here:
https://github.com/viblo/pymunk/blob/master/chipmunk_src/src/cpArbiter.c#L142
https://github.com/viblo/pymunk/blob/master/chipmunk_src/src/cpArbiter.c#L158

**Comment by viblo** [comment]
Closing since my last comment didnt get any reply. Can reopen again if needed.
