### ISSUE TITLE
github links do not work from pymunk website

### ISSUE THREAD

**Issue by illume** [viblo/pymunk#142]
Hello,

on firefox I noticed the content security policy blocks people from going from the pymunk website to the pymunk github.
<img width="922" alt="screen shot 2018-09-03 at 21 15 37" src="https://user-images.githubusercontent.com/9541/44999564-884a0700-afbe-11e8-8285-acdc2ede88e7.png">

On Safari, I don't get the message... the link just doesn't work. When you click on it, it just does nothing.

**Comment by viblo** [comment]
Thanks for the report! 
However, for me the github links works fine in Firefox? Which version do you use, and on what platform?

**Comment by illume** [comment]
Hi again,

I think it has to do with the 'pymunk.org' domain without the www. part. Which seems to use a frame, which then causes the security issue.

By using 'www.pymunk.org' the github link works.

```
curl http://pymunk.org
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Frameset//EN" "http://www.w3.org/TR/html4/frameset.dtd">
<html>
	<head>
		<title>pymunk</title>
		<meta HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=utf-8">
		<meta name="description" content="">
		<meta name="keywords" content="">
		<meta name="viewport" content="initial-scale=1.0, maximum-scale = 1.0, width=device-width">
	</head>
	<frameset style="width: 100%; height: 100%; border: none; padding: 0px; margin: 0px;" rows="*">
		<frame src="http://www.pymunk.org" name="loopiaForwardFrameQwEiyaSSS1">
		<noframes>
			<body>
				<script language="JavaScript" type="text/JavaScript">
					<!--
						document.location.href = 'http://www.pymunk.org'
						//-->
					</script>
				</body>
			</noframes>
		</frameset>
	</html>
	```

**Comment by viblo** [comment]
Thanks, now I could recreate the problem. 
That there is a frame at all is a bit strange, I will investigate a bit. The actual content is hosted at readthedocs and I haven't touched the setup for in long time.

**Comment by viblo** [comment]
I did some updates on the dns and forwarding of the base pymunk.org domain yesterday. No more frames! It would be great if you could try again and see if you can repro the problem. A nice side effect is that the page can now be served over https.

**Comment by illume** [comment]
nice one :)
