### ISSUE TITLE
mac and linux binary wheels

### ISSUE THREAD

**Issue by illume** [viblo/pymunk#146]
Moving this from the comments in the other closed issue.
https://github.com/viblo/pymunk/issues/143#issuecomment-433402962

We're using pymunk in the pygame community game (stuntcat!),
and I would like to contribute this.
https://github.com/pygame/stuntcat/issues/46

- [x] make travis config to create a mac wheel.
- [x] add manylinux wheels code to pymunk
- [x] make travis upload wheels and an sdist .tar.gz on release (in draft mode).
- [ ] how to do the rename hack?

Uploading from travis to github releases is here: https://stackoverflow.com/questions/12343452/how-to-publish-artifacts-in-travis-ci

pymunk fork for this work is here: https://github.com/illume/pymunk?organization=illume&organization=illume

---

For pygame we make them using travisci, so I guess copying the config over might work with a bit of editing. https://github.com/pygame/pygame/tree/master/buildconfig/ci/travis

Actually, could probably delete quite a bit of it, because I don't think pymunk has any dependencies like pygame does?

There's also code to make binary wheels for 'manylinux'.
https://github.com/pygame/pygame/tree/master/buildconfig/manylinux-build

And for windows with appveyor.
https://github.com/pygame/pygame/tree/master/buildconfig/ci/appveyor

---

@viblo said: "Agree about the compiling. I think it should be quite easy since Pymunk only compiles a shared library which is called during runtime from Python/cffi. The windows binary wheels already have a little renaming hack to make them work across Python versions since the shared library does not depend on the Python version, so one 32bit and one 64bit version covers all (normal) Windows Pythons."

**Comment by illume** [comment]
I put in the scripts to build manylinux binary wheels into #148 .
Seems .travis.yml file already has mac bdist_wheels being made.

Another PR is for uploading files to a draft github release when making a tag. https://github.com/viblo/pymunk/pull/149

**Comment by viblo** [comment]
Thanks for the PRs! Will take a closer look

**Comment by illume** [comment]
hi ya,

I did some testing on another repo... and there are a few things I need to fix in these PRs.
For some reason Travis was giving me an error when trying to test on my fork of pymunk. But I think if I push to a new repo it will let me test it.

Anyway, I don't want to waste your time with this... please give me a day or so to fix the issues and test it properly first.

cheers,

**Comment by illume** [comment]
I had to make a fix to: https://github.com/viblo/pymunk/pull/149

It should be ready to go now.

**Comment by viblo** [comment]
Today I made a new rel of pymunk, with binary wheels for osx and linux on pypi , so this should be resolved now. :)

**Comment by illume** [comment]
Great! Thank you very much.
