### ISSUE TITLE
issue with cx_freeze

### ISSUE THREAD

**Issue by illume** [viblo/pymunk#150]
There is a fix in a PR to cx_freeze here: https://github.com/anthony-tuininga/cx_Freeze/pull/445

( if random internet surfer arrives here and the PR hasn't been merged into a release... you can also use a monkey patch in your setup.py like here: https://github.com/pygame/stuntcat/pull/52/files )

**Comment by illume** [comment]
The PR made the .dll be copied in twice. 

I think the pymunk code needs to look elsewhere for the .dll. Will investigate a fix.

**Comment by viblo** [comment]
Thanks for looking into cx_Freeze. Not something that I remember anyone tried before. Would be great if pymunk could do something to make it better. As Im sure you have already seen _libload.py does a little bit of logic to help with bundling/freezing, so if something more is needed Im all for it.

**Comment by illume** [comment]
Thanks for the pointer :) I'll have a look, and whip up a PR sometime in the next few days.

**Comment by illume** [comment]
I made the fix, and it works with cx_freeze now. See PR #153 

It's quite likely pymunk will work with other "module scanning" packaging tools as well because of this. Because pycparser imports those files dynamically with `exec()` weirdness rather than using `import`.
