### ISSUE TITLE
cx_freeze pycparser lextab yacctab missing

### ISSUE THREAD

**Issue by illume** [viblo/pymunk#151]
A separate issue with cx_freeze is with lextab.py and yacctab.py. They are attempted to be made at runtime, however permission is denied to them. It seems these do not need to be generated at runtime and can be included. I found searching the web various other projects including them.

Reported issue here: https://bitbucket.org/cffi/cffi/issues/392/lextab-yacctab-not-included-with-cx_freeze

**Comment by viblo** [comment]
Fixed by #152
