### ISSUE TITLE
pymunk with pyinstaller

### ISSUE THREAD

**Issue by illume** [viblo/pymunk#154]
I made a test here:
https://github.com/pyinstaller/pyinstaller/pull/3922

But it seems to be failing with `pymunk==5.4.0` and git pymunk.

```bash
git clone git@github.com:illume/pyinstaller.git
git checkout pymunk-test
python3 -m venv venv
. ./venv/bin/activate
pip install -r tests/requirements-tools.txt
pip install pymunk
pytest tests/functional/test_libraries.py -k test_pymunk
```

**Comment by zipandrar** [comment]
pymunk can work well with nuitka... ...

**Comment by eruvanos** [comment]
Hi, I had a look on the code and the concept of PyInstaller. From my point of view it looks like some small changes will make this work easier.

In the [lib loading code](https://github.com/viblo/pymunk/blob/40a378068f245706ef59bea323e745a48ee5ccdd/pymunk/_libload.py#L42)
the binary is searched in either a side-package.zip or next to the executable.

In case of PyInstaller (especially with --onefile) the binary will be in a temporary folder `sys._MEIPASS`.
Would it be possible to check for this directory or at least check in the current working directory?

Regards

**Comment by viblo** [comment]
Oh. Did you experience the issue yourself? Or you mean that it doesnt work with onefile option?

There is a pyinstaller example included in pymunk, so in some cases it should work at least. Main reason I kept this issue open was that the linked PR was open. 

Im in the process of rewriting the binding logic with CFFI to not use a standalone dll but instead a python extension module. That means (among many other changes) that `_libload.py` will be removed. Hopefully the new version (Pymunk 6.0) will work even better with PyInstaller, or if not it will at least require different fixes.

(If you have a specific reason that you need it fixed for current version I can of course try to make a fix release of the current Pymunk as well)

**Comment by eruvanos** [comment]
Fixing it for the current version would be great!

I got it working without the `onefile `option, or by coping it over into the executable path.
But still would be nice to either search in current path, so I can change the working directory to the `sys._MEIPASS` dir on startup (as a workaround). Or directly check if `sys._MEIPASS` is set and search for the binary in that path.

With such a change using pymunk in a `onefile ` setup would be as easy as in a folder setup.

Thank you for the quick response!

**Comment by viblo** [comment]
Alright, I will try to include a fix in the next minor release of pymunk! Leaving the issue opened until its implemented.

**Comment by eruvanos** [comment]
Maybe you think about adding a hook to PyInstaller ;)

**Comment by mistergates** [comment]
This is how I fixed it for my app, added the following to `_libload.py`:

```
if getattr(sys, 'frozen', False):
        lib_path = os.path.join(sys._MEIPASS, libfn)
```

This was added right before the `lib = ffi.dlopen(lib_path)` block. 

Not sure this is the best route, but seems to be working well for me so far.

**Comment by SirGnip** [comment]
I was having the same issue and was about to create a new Issue when I saw this one!  So FWIW, pyinstaller 4.0 would package up pymunk 5.6.0 just fine with:

`pyinstaller example.py --add-binary "c:\myrepo\min_pymunk\venv\Lib\site-packages\pymunk\chipmunk.dll;."`

...and would run fine.  But, when I added `--onefile` to the command: 

`pyinstaller example.py --add-binary "c:\myrepo\min_pymunk\venv\Lib\site-packages\pymunk\chipmunk.dll;." --onefile`

...the pyinstaller packaging would complete successfully. But when I ran the bundled .exe I would get this error:

`OSError: cannot load library 'C:\Users\user\AppData\Local\Temp\_MEI178482\chipmunk.dll': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'C:\\Users\\user\\AppData\\Local\\Temp\\_MEI178482\\chipmunk.dll'`

Is there a pymunk 5.6.1 release planned by chance?  Or, is this fix scheduled to go out with pymunk 6.0.0?

**Comment by viblo** [comment]
I will make a 5.6.1 (or 5.7) release with this fix included. The next major version will drag a bit, and it seems like several people are affected by this issue so better to fix it first.

**Comment by viblo** [comment]
Pymunk 5.7.0 out now. Would be great if you could try it out.

**Comment by SirGnip** [comment]
I just installed Pymunk 5.7.0 and did both:

`pyinstaller example.py --add-binary ".\venv\Lib\site-packages\pymunk\chipmunk.dll;."`
...and...
`pyinstaller example.py --add-binary ".\venv\Lib\site-packages\pymunk\chipmunk.dll;." --onefile`

Both .exe's that were generated ran without error.  So, looks like the fix works!  Many thanks for the fix and quick release!

**Comment by viblo** [comment]
Great!
