### ISSUE TITLE
Is there any way to constrain two objects to simply not collide?

### ISSUE THREAD

**Issue by fraserprice** [viblo/pymunk#157]
I am building a simulation for a robot arm which has 3 segments- these are connected by PinJoint constraints, each being motorised. My issue is that the first and third segments collide, as there is no constraint directly between them so I cannot set `collide_bodies` to `False`. I want them to collide with other objects in my Space, just not with the other limb segments.

Subclassing `Constraint` also doesn't seem possible as the underlying C code needs to be altered to support this.

Is there any way to achieve this?

**Comment by fraserprice** [comment]
EDIT: Looks like I missed the `CollisionHandler` class, sorry for my negligence!

**Comment by viblo** [comment]
Great that you figured it out. I just want to add that another way to do waht you want is by setting the shape filter on the shapes: http://www.pymunk.org/en/latest/pymunk.html#pymunk.ShapeFilter
