### ISSUE TITLE
Standalone example programs required for all functionalities of pymunk. Especially joints and constraints

### ISSUE THREAD

**Issue by nav9** [viblo/pymunk#159]
One of the most outstanding benefits of Pymunk (compared to other 2D physics libraries) is that it gives a newcomer a hassle-free installation and some [excellent demo's](http://www.pymunk.org/en/latest/examples.html). But when the newcomer wants to understand how the various joints and constraints work, there's not much explanation available. [Shapes for draw demos](https://github.com/viblo/pymunk/blob/master/examples/shapes_for_draw_demos.py) does not help because the objects don't move and it takes a long time for one to figure out how to take that code snippet and create a working example where the working of the joint/constraint can be attempted. I'm currently going through that exact same problem. [Chipmunk's video](https://www.youtube.com/watch?v=ZgJJZTS0aMM) doesn't help because the grids aren't labelled. Even for functions like getting the Collision set, raycasting etc, it would help a lot to have tiny example programs for that specific functionality.

To the experienced person these may seem trivial, but it would help if you understand that many of us have to learn so many programming languages that it would help a lot if we had a readymade standalone example that clearly showed a particular functionality, rather than have to search for code snippets, then refer the API and then try to understand why objects are bouncing uncontrollably etc. The [queries on stackoverflow](https://stackoverflow.com/questions/tagged/pymunk) prove my point. It would just save everyone so much more time if descriptive, short examples are created for every feature that Pymunk has. It would also position Pymunk in a far superior position to any other 2D physics library. 
Thank you.

**Comment by viblo** [comment]
Thanks for the input. 

The chipmunk video used to have annotations so you could see which constraint each box contains, but seems like its not there anymore. 

For some things (mostly smaller features) I think the unit tests are quite useful. They can for example show for how sensor shapes work. But for constraints you dont learn a lot from the unit tests and I agree that something like the code that produced that video would be a useful addition to the examples. I will put it on the todo.

**Comment by nav9** [comment]
Looking at the unit tests for examples is a good idea. Thank you. About joints and constraints, it would also help to have examples where the joint can be rotated programmatically, for example, to create a walking spider (which I'm struggling to create now) or steam engine. 
As mentioned, the StackOverflow questions can provide pointers on most common problems faced.

**Comment by davinellulinvega** [comment]
The main problem I encounter even before setting up joints and constraints, is the documentation. The API reference is well written and detailed, but what the documentation lacks in my opinion is a section describing the philosophy behind pymunk. This is already done to some degree in the Overview, but I had a hard time understanding the concept of collision types and shape filters, and how this all impact my simulation. All I wanted to do was implement a simple reinforcement learning environment where a robot, with proximity sensors, can learn to avoid obstacles. I spent a week trying to understand how I could simulate sensors and get distance readings using the different collision handlers.
Relying on examples to explain how pymunk works and should / can be used is, again in my opinion, not the best way. Examples should be here to illustrate a point.
Aside from this (kind of) rant, this is a beautiful library and deserves more love.

**Comment by nav9** [comment]
I agree with davinellulinvega. But perhaps we must also realize that it is just as important for us to contribute to open source. Victor has provided us an excellent Python binding for Chipmunk. Rather than expect him to do all the hard work, perhaps we can also contribute our time and knowledge to support Pymunk. By mid May, I plan to write a few small tutorials explaining some parts of Pymunk. Hope you could also write some tutorials, davinellulinvega. Victor is of course the best person to write an in-depth explanation.

**Comment by davinellulinvega** [comment]
You are entirely correct. However, having picked up Pymunk only two days ago, I do think I am on the wrong side of the fence, to pretend I can teach anything to anyone yet. My previous message, was not directed at Victor, but rather to the whole community (especially those who have experience in using Pymunk and/or chipmunk). On my end, I'll do a few POCs to test and gain a deeper understanding of Pymunk, and I'll contribute after my upcoming project, which heavily relies on this lovely library.

**Comment by viblo** [comment]
Its great to get some feedback what can be improved, especially when its somethings specific. At minimum I can add it to the list of stuff to do and get some feeling for its importance.. (However, as with most of the development of Pymunk no promises if/when)

**Comment by viblo** [comment]
I have just committed a port of the joints demo from Chipmunk. I will close this issue, if there are other specific examples or docs that would be good a new issue can be opened.

**Comment by nav9** [comment]
As promised, I've created a small tutorial: https://nrecursions.blogspot.com/2019/05/pymunk-tutorial.html
