### ISSUE TITLE
pymunk website seems missing (read the docs message)

### ISSUE THREAD

**Issue by illume** [viblo/pymunk#163]
Hey hej,

the pymunk website (http://www.pymunk.org/en/master/) seems missing (read the docs message).

However this is here: https://pymunk.readthedocs.io/en/latest/

Maybe the `en/master` path stopped being a thing. It doesn't work here: https://pymunk.readthedocs.io/en/master/ either.

**Comment by viblo** [comment]
Thanks. Yes, there seems to be some confusion between master and latest. Readthedocs have behaved a bit strange lately. Im pretty sure it worked yesterday, and now after clicking around a bit in the admin interface it seems to work again (felt like it was some cacheing issue). Can you check again?

**Comment by illume** [comment]
<img width="571" alt="image" src="https://user-images.githubusercontent.com/9541/57193947-1b1db580-6f41-11e9-9425-6a0ba8e36e2d.png">

**Comment by illume** [comment]
Oh. If I go to http://www.pymunk.org/ it redirects to http://www.pymunk.org/en/latest/ now.

**Comment by illume** [comment]
I guess the `en/master` part was in my history still.

**Comment by illume** [comment]
🎉
