### ISSUE TITLE
possible to get applied force to static body?

### ISSUE THREAD

**Issue by jonasenander** [viblo/pymunk#164]
Short version:
I have a scene in which a box pushes against a wall. The wall is a static body. Is there a way to get the force that is applied unto the wall?

Longer version:
I have a scene as in the image. Two boxes (magenta and gray) with a slidejoint between. There are a DampedSpring on each side of the magenta box that connects unto the gray box (blue and red thick lines). There is a wall hanging from the "sky" (green).

![Artboard 1](https://user-images.githubusercontent.com/365309/57228502-37d6ed80-7014-11e9-871c-534e33d2a880.jpg)

I activate the A DampedSpring and thus the magenta box moves left towards the green wall, when it hits the wall the gray box will start to slide to the right.
I need the force generated by the DampedSpring A, The force applied to the magenta box (B) and also the force applied to the gray box (C) (which is the same thing as the force applied unto the wall).

I have read the documentation up and down and cant figure this very simple problem out. Please help!

**Comment by viblo** [comment]
I think it should be possible. 
A: To get the force for DampedSpring, take a look at the impulse: http://www.pymunk.org/en/latest/pymunk.constraint.html#pymunk.constraint.DampedSpring.impulse (available on all types of constraints).
B/C: I think you need to have a collision callback for this to work. Then in the callback you will get the Arbiter for the collision, and can check for example total_impulse or total_ke. http://www.pymunk.org/en/latest/pymunk.html#pymunk.Arbiter
There is no perfect example, but maybe this one will help: https://github.com/viblo/pymunk/blob/master/examples/contact_and_no_flipy.py It uses how deep the collision is to draw the collision, but you could easily modify that code to look at the arbiter.total_impulse for example.

**Comment by jonasenander** [comment]
Thank you for your response. 

If I start from the top:
If I look into the impulse for A during the movement and divide it with delta time, I will get the force (as by your answer and the documentation). But if I at the same time look into the impulse/force of the red DampedSpring I will get an (almost) equal force in the opposite direction, even though I have set the siffness to zero. Do you know why that is? If I calculate the net difference, what would that be equal to? The force that is acted upon the magenta box that is the cause for acceleration? 

B/C: The total_impulse that I get from the collision between the magenta and green boxes. Which force is that equal to? The documentation states "that it is the impulse that was applied this step to resolve the collision", but I do not intuitively understand what is meant by "resolving" a collision. 

Kinetic energy is not useful to me since I am interested in the force acted upon the bodies, even if there is no movement as a result.

Thank you for your time.

**Comment by jonasenander** [comment]
I will update my own questions somewhat:

1) The equal impulse/force of the red DampedSpring, is a reaction to the impulse of A (?). I've read the source code for Chipmunk, but Im no C-programmer so I not sure I follow everything. But I still am not sure how to calculate the net force that is applied unto the magenta box at each timepoint. Anyone who can verify this?

2) Still no idea what impulse means in relation to "resolve" a collision.

3) The .force is always zeros since it is always set to zero in the c-library during the stepping function, and it only carries a value during the stepping function if it has been set by the programmer before running the step function. And as such never holds the calculated force as generated by various constraints etc.
As far as I understand the source code for Chipmunk.

**Comment by viblo** [comment]
Unfortunately Im not 100% confident about how it works either. As you have already noticed the core simulation is done by the Chipmunk c library, and in my own usage the exact definition has not been very important. Previously I would recommend you to ask in the chipmunk forum, but nowadays its mostly dead. What you can try is to search there for old questions on this topic there (I tried myself, but didnt find a exact answer).

1/2:

(I guess you saw that, but if not: it seems like the impulse of the spring includes the damping, so if you have a spring with zero stiffness and nonzero damping there will be a nonzero impulse returned: https://github.com/slembcke/Chipmunk2D/blob/master/src/cpDampedSpring.c#L75 )

Maybe these threads from the chipmunk forum can help a little bit:
https://chipmunk-physics.net/forum/viewtopic.php?f=1&t=2175
https://chipmunk-physics.net/forum/viewtopic.php?t=2716 

3. Yes exactly, I guess the documentation could be more clear about this, Ill make an update.

Sorry that I cant give you a more straight answer.

**Comment by jonasenander** [comment]
Ok, I think I have a solution.

1: It was the damping. If I modulated the damping as well as the stiffness of the DampedSpring the reactive force in the red DampedSpring disappeard. Furthermore, when the red DampedSpring has 0.0 stiffness and 0.0 damping the impulse of A makes a lot more sense with regards to the B and C forces. Because, as long as the Magenta box does not touch the Green wall the impulse generated by A will primarily affect the Magenta box, but when the Magenta box touches the green wall the impulse builds until the Gray box starts to move and then the impulse decreases. 

Thank you for your help. It was vital to understand this.

**Comment by viblo** [comment]
Great that you managed to figure out the problem 👍
