### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'tell'

### ISSUE THREAD

**Issue by soccerrprp** [viblo/pymunk#166]
Greetings,

Getting an error while compiling the kivy-pymunk example:

 File "C:\Program Files\lib\imghdr.py", line 19, in what
     location = file.tell()
 AttributeError: 'NoneType' object has no attribute 'tell'

Any ideas what is causing this?

Thank you.

**Comment by viblo** [comment]
From your description it doesn't look like it's the kivy-pymunk example
that creates the problem. But to know better it would be good with more
info.
Some good questions that could be helpful are:
What python are you using, which os are you using and what command are you
using to compile?

**Comment by soccerrprp** [comment]
Greetings,
Sorry about that. I am using python 3.6.8, Windows 10 and I am using Eclipse to compile/run. Should I using CMD instead? 

Thank you. 

Richard Perrine"A truly rich man is one whose children run into his arms when his hands are empty." 
 ~Unknown Author

The true sign of intelligence is not knowledge but imagination.[Albert Einstein]

My Blog
 

    On Tuesday, June 11, 2019, 11:27:06 AM MDT, Victor <notifications@github.com> wrote:  
 
 From your description it doesn't look like it's the kivy-pymunk example
that creates the problem. But to know better it would be good with more
info.
Some good questions that could be helpful are:
What python are you using, which os are you using and what command are you
using to compile?

**Comment by viblo** [comment]
I wonder if it can be because the code cant find the two pictures it needs, which are in the same folder.. Maybe eclipse doesnt set the current directory properly.
Can you try to run it from command line with `python main.py`, and then paste all the output here?

**Comment by soccerrprp** [comment]
Victor,
Thank you, but found the solution. It appears that the images I downloaded are not a recognized format(?). I replaced the image(s) with a png that I created and it worked. Odd. 

Richard Perrine"A truly rich man is one whose children run into his arms when his hands are empty." 
 ~Unknown Author

The true sign of intelligence is not knowledge but imagination.[Albert Einstein]

My Blog
 

    On Tuesday, June 11, 2019, 2:26:25 PM MDT, Victor <notifications@github.com> wrote:  
 
 
I wonder if it can be because the code cant find the two pictures it needs, which are in the same folder.. Maybe eclipse doesnt set the current directory properly.
Can you try to run it from command line with python main.py, and then paste all the output here?

**Comment by viblo** [comment]
Ok, great that you managed to fix it.
