### ISSUE TITLE
PyMunk Body position and chipmunk shape position disagree?

### ISSUE THREAD

**Issue by justinkterry** [viblo/pymunk#169]
Look at this short video: https://www.youtube.com/watch?v=a6kxx3-_i54

What's happening is that the blue circle in the foreground is being drawn by pymunk debug mode, while the dark grey circle in the back is being drawn by pygame as the coordinates of body.position (minus the radius). As you can see, they don't agree in many cases after movement, and this can't be accounted for with center of mass or anything else I can find. I've spent the past 2 hours going through the source code, and the position of the circle drawn in debug mode is taken in the C portion of chipmunk from the position of the circle shape. Can this be fixed, or can part the pymunk API be extended to give acces to the position/center properties for shapes present in the C API?

Code below:

```
import pymunk
import pymunk.pygame_util
import pygame
import os
import random
import math
_image_library = {}

pymunk.pygame_util.positive_y_is_up = False


def get_image(path):
    global _image_library
    image = _image_library.get(path)
    if image is None:
        canonicalized_path = path.replace('/', os.sep).replace('\\', os.sep)
        image = pygame.image.load(canonicalized_path)
        _image_library[path] = image
    return image


def add_ball(space, x, y):
    mass = 10
    radius = 35
    inertia = pymunk.moment_for_circle(mass, 0, radius, (0, 0))
    body = pymunk.Body(mass, inertia)
    body.position = x, y
    body.angular_velocity = random.uniform(-2*math.pi, 2*math.pi)  # radians/s
    shape = pymunk.Circle(body, radius, (0, 0))
    shape.friction = .64
    shape.elasticity = .3
    space.add(body, shape)
    return body

def add_piston(space, x, y):
    piston = pymunk.Body(body_type=pymunk.Body.KINEMATIC)
    piston.position = x, y
    segment = pymunk.Segment(piston, (0, 0), (25, 0), 5)
    segment.friction = .64
    segment.color = pygame.color.THECOLORS["blue"]
    space.add(segment)
    return piston


def movePiston(piston, v):

    def cap(y):
        if y > 394:
            y = 394
        elif y < 346:  # 394-48
            y = 346
        return y

    piston.position = (piston.position[0], cap(piston.position[1] - v*3))


"""
    if piston.position[1] < 394 and piston.position[1] > 370:  # 394-370
        piston.position = (piston.position[0], min(piston.position[1] - v*3, 394))
"""


def add_walls(space):
    walls = [pymunk.Segment(space.static_body, (70, 70), (770, 70), 1)
                , pymunk.Segment(space.static_body, (70, 70), (70, 420), 1)
                , pymunk.Segment(space.static_body, (70, 420), (770, 420), 1)
                , pymunk.Segment(space.static_body, (770, 70), (770, 420), 1)]

    for wall in walls:
        wall.friction = .64
        wall.color = pygame.color.THECOLORS["green"]
        space.add(wall)


pygame.init()
screen = pygame.display.set_mode((840, 490))
pygame.display.set_caption("pistonBall")
done = False
clock = pygame.time.Clock()

ballSprite = get_image('ball2Line.png')
pistonSprite = get_image('smallPiston3.png')
background = get_image('background.png')

space = pymunk.Space(threaded=True)
space.threads = 2
space.gravity = (0.0, 900.0)
space.collision_bias = .00001

pistonList = []
for i in range(20):
    piston = add_piston(space, 5+70+35*i, 394 - random.randrange(0, 24, 3))
    pistonList.append(piston)

ball = add_ball(space, 731, 250)

add_walls(space)

draw_options = pymunk.pygame_util.DrawOptions(screen)

i = 19

while not done:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            done = True
        if event.type == pygame.KEYDOWN:
            if event.key == pygame.K_a:
                i -= 1
                i = max(0, i)
            if event.key == pygame.K_d:
                i += 1
                i = min(19, i)
            if event.key == pygame.K_s:
                movePiston(pistonList[i], -1)
            if event.key == pygame.K_w:
                movePiston(pistonList[i], 1)

    screen.blit(background, (0, 0))
    screen.blit(pygame.transform.rotate(ballSprite, -1*math.degrees(ball.angle)), (ball.position[0]-35, ball.position[1]-35))  # (ball.position[0]-35, ball.position[1]-35)
    space.reindex_shapes_for_body(ball)
    space.reindex_static()
    space.debug_draw(draw_options)

    for piston in pistonList:
        screen.blit(pistonSprite, (piston.position[0]-5, piston.position[1]-5))

    space.step(1/15.0)
    pygame.display.flip()
    clock.tick(15)


"""
slightly random initial position
stop "bouncing through" issue
fix ball skinning
make sure im using pymunk pro, with all optimizations
add human mode and stripped down AI mode (add +human to everything to deal with conversion)
profile AI mode
plug into pytorch
"""
```

**Comment by viblo** [comment]
The position and angle of a body does already come from chipmunk more or less directly, as seen here: https://github.com/viblo/pymunk/blob/master/pymunk/body.py#L209 and here https://github.com/viblo/pymunk/blob/master/pymunk/body.py#L252

space.debug_draw draws using the built in drawing logic in chipmunk, but I would be surprised if it doesnt match the actual positions. 

I suggest you try to draw the ball with `pygame.draw.circle` instead of the sprite. So
`screen.blit(pygame.transform.rotate(ballSprite, -1*math.degrees(ball.angle)), (ball.position[0]-35, ball.position[1]-35))`
becomes `pygame.draw.circle(screen, pygame.color.THECOLORS["red"]`, (int(ball.position[0]), int(ball.position[1])), 35)` and see if there's still any mismatch.

**Comment by justinkterry** [comment]
Using pygame.draw.circle works as expect, you're right. I checked to make sure, and my ball sprite perfectly matches the circle drawn by the debugger too. Any idea how pygame could be drawing the sprite to a variably wrong location, or what I should look into for that?

**Comment by viblo** [comment]
Two things that can be suspicious: 
1. Why rotate the sprite with negative angle (`-1*`)?
2. How big is the sprite exactly?

**Comment by viblo** [comment]
Will close this. Feel free to comment again if you need more support.

**Comment by justinkterry** [comment]
Hey this issue is still going on, I'm just now getting back to the project. I scaled the image down to 70,70 exactly (so the issue wasn't that), and while the draw circle works right as i said, the sprite circle is still consistently off:

![image](https://user-images.githubusercontent.com/19422700/69506268-d9b02000-0efb-11ea-990f-6ac91e07b124.png)

I've attatched the images so you can run the game/ look at them yourself

![image](https://user-images.githubusercontent.com/19422700/69506305-09f7be80-0efc-11ea-986e-50bf2a76e9a8.png)

![image](https://user-images.githubusercontent.com/19422700/69506309-0ebc7280-0efc-11ea-8022-13fe4acb9de3.png)

![image](https://user-images.githubusercontent.com/19422700/69506322-1bd96180-0efc-11ea-8953-1552e97fa841.png)

**Comment by viblo** [comment]
Ah ok, I see now that I missed to give you one last piece of info, you need to offset the drawing with the sprites size after it has been rotated. Like this:
```
    rotated_surface = pygame.transform.rotate(ballSprite, math.degrees(ball.angle))
    offset = pymunk.Vec2d(rotated_surface.get_size()) / 2.
    screen.blit(rotated_surface, ball.position-offset)
```

You can see this in the using sprites example: https://github.com/viblo/pymunk/blob/master/examples/using_sprites.py
