### ISSUE TITLE
Add function to space object to change number of iterations

### ISSUE THREAD

**Issue by justinkterry** [viblo/pymunk#170]
This is in the chipmunk C API not pymunk, and it would be really useful to change the number of iterations used in the physics simulation so you could control accuracy/performance trade offs if you wanted to.

**Comment by viblo** [comment]
You can already do this, unless you mean something different.. See https://github.com/viblo/pymunk/blob/master/pymunk/tests/test_space.py#L34
Like this: `myspace.iterations = 3`

**Comment by justinkterry** [comment]
Right, sorry
