### ISSUE TITLE
aafig dependency for [dev] extra flag is missing from PyPI

### ISSUE THREAD

**Issue by qxcv** [viblo/pymunk#172]
When I try to install this package from f6c5c0b9f7308f77092bbf4d2e8969a95dd39810 with the `[dev]` extra flag, I get this error:

```
pymunk$ pip install -e '.[dev]'
Obtaining file:///home/sam/repos/pymunk
Requirement already satisfied: cffi!=1.13.1 in /home/sam/.virtualenvs/milbench/lib/python3.6/site-packages (from pymunk==5.6.0) (1.13.2)
Requirement already satisfied: pyglet in /home/sam/.virtualenvs/milbench/lib/python3.6/site-packages (from pymunk==5.6.0) (1.4.6)
Requirement already satisfied: pygame in /home/sam/.virtualenvs/milbench/lib/python3.6/site-packages (from pymunk==5.6.0) (1.9.6)
Collecting sphinx
  Using cached https://files.pythonhosted.org/packages/1d/58/a547b02946af1cf337c701cafcf3267065c1c83d6e701f540961f4907b5d/Sphinx-2.2.1-py3-none-any.whl
ERROR: Could not find a version that satisfies the requirement aafig (from pymunk==5.6.0) (from versions: none)
ERROR: No matching distribution found for aafig (from pymunk==5.6.0)
```

The same thing happens when installing from PyPI with `pip install pymunk[dev]`. I suspect the `aafig` dep in `setup.py` is meant to be either `aafigure` or `sphinxcontrib-aafig`, but I'm not sure which. This is not a big deal given that the `dev` flag doesn't have any effect beyond installing some optional dependencies, but it's probably also an easy fix :smile:

**Comment by viblo** [comment]
Thanks! I have committed a fix. It is indeed supposed to be `aafigure` that is installed.
