### ISSUE TITLE
Version Migration Guides?

### ISSUE THREAD

**Issue by hawkerm** [viblo/pymunk#173]
I have a Python 2 project using Pymunk 3.0 still that I'm trying to upgrade to Python 3 and Pymunk 5.6.

I didn't see any guides in the documentation or website news posts, about specific migration notes between versions of Pymunk.

Does anything like this exist?  It'd be nice to know when I see an error about something missing where it's gone or what the equivalent is.

For instance, `set_default_collision_handler` is my first one.

**Comment by viblo** [comment]
Short answer is no, unfortunately there's no migration docs as such.

For the collision handler you are now supposed to use the `add_default_collision_handler()`, and then you get a collision handler object back on which you can set the callbacks. If you have other issues feel free to write them in this thread and I will try to answer them

**Comment by hawkerm** [comment]
Thanks @viblo, I ended up discovering that from another older thread after.  I've managed to get [some of my code working](https://github.com/Mikeware/SpaceBattleArena/commit/638e8f4b72b5084721c20e338b69c4c7b2b4d688), but haven't tested all the functionality yet as I have to convert some network code over to Python 3 still, 

Any extra details/caveats to the following swaps I did would be nice to know though:

- Switching `get_points` to `get_vertices` on Shape
- On Body, is `apply_impulse_at_local_point` the most suitable direct swap for `apply_impulse`?

**Comment by hawkerm** [comment]
Ah, hit a new more subtle issue.  I used to manipulate the body's positions in order to create a torus space and wrap around the edges of the screen:

```py
                    # Wrap Object in World
                    if obj.body.position[0] < 0:
                        obj.body.position[0] += self.width
                    elif obj.body.position[0] > self.width:
                        obj.body.position[0] -= self.width
                    if obj.body.position[1] < 0:
                        obj.body.position[1] += self.height
                    elif obj.body.position[1] > self.height:
                        obj.body.position[1] -= self.height
```

However, now these seem immutable and will not update.  Even if I use the `x` and `y` properties instead of the index.  Do I need to recreate the entire Vector object to move the position or is there a different pattern I should use here?

Also now hitting this from Space's `add_post_step_callback`:
```
  File "C:\Users\\AppData\Local\Programs\Python\Python38\lib\site-packages\pymunk\space.py", line 408, in step
    self._post_step_callbacks[key](self)
  File "C:\Users\\AppData\Local\Programs\Python\Python38\lib\site-packages\pymunk\space.py", line 521, in f
    callback_function(self, key, *args, **kwargs)
TypeError: myfunction() takes 3 positional arguments but 4 were given
```

Do I need to specify the **kwargs even if they're not used now?

**Comment by viblo** [comment]
Positions are easy to fix. You need to set the full position-vector, for example like this
`obj.body.position = obj.body.position[0] - self.width, obj.body.position[1]`

For the post step callback the update is that the callback function has space as an additional argument, passed first. If you do not need the space object you can just ignore it (but you need to update the signature of the callback function).

**Comment by hawkerm** [comment]
Thank for all the help @viblo, glad it's been a pretty easy swap-out for everything so far. I need to get my test-suite back online to run through more scenarios, but all the basic stuff seems to be working for now!

**Comment by hawkerm** [comment]
Ah, spoke too soon, just noticed something.  Looks like the simple `Shape.group` moved to [ShapeFilter](http://www.pymunk.org/en/latest/pymunk.html#pymunk.ShapeFilter)?

So what was just:
```
self.shape.group = 1
``` 

becomes this instead:
```
self.shape.filter = pymunk.ShapeFilter(group=1)
```

That seemed to work :)

**Comment by viblo** [comment]
Yes exactly. The filtering properties has been collected into a separate class. (In this way its easy to use the same filters on many objects)

**Comment by hawkerm** [comment]
Ah, I missed that `get_points` used to return world coordinates, but the new `get_vertices` returns local, so I need to follow the guide [in the doc](http://www.pymunk.org/en/latest/pymunk.html#pymunk.Poly.get_vertices).

**Comment by hawkerm** [comment]
Also, I used to be able to modify the `body.velocity.length` directly, but now it seems that's changed as well?  Can I only update it in the `velocity_func` or do I just need to set the whole velocity object like we had to do with the positions?

**Comment by hawkerm** [comment]
Changing from `body.velocity.length -= amt` to 
```
body.velocity = Vec2d(body.velocity.length - amt, 0).rotated(body.velocity.angle)
```
seems to work, but seems excessive to create a new vector each time.

Looking at the Vec2d code, it appears unchanged in the set_length property method, so I'm confused on why this stopped working between my change from Python 2 to 3 and Pymunk 3 to 5?

Though I'm really just trying to apply a slowing down force in the direction of travel (I calculate my amount above based on the brake force, mass, and time passed); so I imagine there'd be some way to do this with applying a local impulse, but my brain isn't working enough at the moment to figure out how to get that vector...

**Comment by viblo** [comment]
When Pymunk changed ffi library from ctypes to cffi for the wrapping the Vec2ds returned/set on the c-level objects became copies, so after that you always have to set the whole Vec2d instead of just x or y on it. I think the older way was easier to work with, but I havent found a good way to implement it with cffi.

You can convert it in this way:
```
body.velocity.length -= amt
# becomes
vel = body.velocity
vel -= amt
body.velocity = vel
```

**Comment by hawkerm** [comment]
Thanks for the explanation @viblo, good to know the history here. I just used this paradigm a lot for various game related slow-down/speed-up mechanics, so I need to go hunting through my code base a bit now. :)

**Comment by viblo** [comment]
closing this now. Feel free to post again / reopen

**Comment by hawkerm** [comment]
Also found out that `velocity_limit` was removed, but looks like that's why there's an added example for that in the `velocity_func` now?

**Comment by viblo** [comment]
Yes exactly.
