### ISSUE TITLE
Installing pymunk in virtualenv (in Windows, but using WSL)

### ISSUE THREAD

**Issue by bonellia** [viblo/pymunk#174]
Hi,
I've got pymunk-5.6.0 and I'm creating a web app using Django.
I managed to set my development environment. I'm using WSL and VSCode in Windows 10, but basically I'm developing in Ubuntu 18.04

In the documents, I read the following part:

> Advanced - Install
> > python setup.py install
> Once installed you should be able to to import pymunk just as any other installed library. pymunk should also work just fine with virtualenv in case you want it installed in a contained environment.
> 

I am a bit lost on where to have pymunk folder (which has setup.py in it) before using setup.py in order to have it installed in my virtual environment. I'm not experienced working in a virtualenv, so if this is a trivial thing or not to be asked in Github issues, apologies.

Previously, I managed to work in VSCode using Windows binaries and libraries of Python and "pip install" was sufficient without virtualenv. I've been also using pymunk for my simulations, but I am kinda switching from desktop app to web app, so I had to change my development environment for Django.

I'll also need this information to add mahplotlib which I will be exporting my simulations as mpeg in order to send to client, but currently I'm not there.

Anyways, thanks in advance.

**Comment by viblo** [comment]
This might be a stupid question, but did you try pip install? And if you
did, what was the problem?

**Comment by bonellia** [comment]
I think I need to simplify my environment.
I have tried to run my test code, but since pyglet cannot be run in WSL, I can't get it to work, so I can't test if pymunk is already installed or not. I've manually browsed directories inside my virtualenv but couldn't find any file related to pymunk. So I assume pip install (pip3 install actually) doesn't install pymunk in virtualenv.

I get the following output when I try to run my test:

```
(gbvenv) kril@kril-w10:/mnt/c/coding/goldberg$ pip3 install pymunk
Requirement already satisfied: pymunk in /mnt/c/Users/Kril/Google Drive/edu/20191/445/goldberg/gbvenv/lib/python3.6/site-packages (5.6.0)
Requirement already satisfied: cffi!=1.13.1 in /mnt/c/Users/Kril/Google Drive/edu/20191/445/goldberg/gbvenv/lib/python3.6/site-packages (from pymunk) (1.13.2)
Requirement already satisfied: pycparser in /mnt/c/Users/Kril/Google Drive/edu/20191/445/goldberg/gbvenv/lib/python3.6/site-packages (from cffi!=1.13.1->pymunk) (2.19)
```

You can have a look on the repository I'm working on, maybe I overlook something very simple.
https://github.com/bonellia/goldberg

Regardless, it's a bit of a mess because I changed from system-wide python and libraries in windows to virtualenv installations in Ubuntu subsystem in Windows 10, using VSCode remote. Most of my imports are also broken atm.

I get the feeling that this is not even a pymunk-related issue, so feel free to close the issue.
Thanks, Taha.

**Comment by bonellia** [comment]
Alright, I'm back in business.
No more OS mixing, WSL is great but it was pointless to do this.
I successfully installed pymunk while working in Windows 10 in a virtualenv.
Sorry for the confusion, I'll close the issue.

![image](https://user-images.githubusercontent.com/16254153/71379601-f44de580-25dc-11ea-8887-e7560d76dbb1.png)

**Comment by viblo** [comment]
Ok, great that you manage to solve your problem :)
