### ISSUE TITLE
Vec2d.get_dist_sqrd documentation

### ISSUE THREAD

**Issue by Qjs** [viblo/pymunk#175]
http://www.pymunk.org/en/latest/_modules/pymunk/vec2d.html#Vec2d.get_dist_sqrd

Currently reads as:
        """The squared distance between the vector and other vector
        It is more efficent to use this method than to call get_distance()
        first and then do a sqrt() on the result.
        
        :return: The squared distance
        """

Should read as:
"""The squared distance between the vector and another vector
        It is more efficient to use this method than to call get_distance()
        first and then do a **2 on the result.
        
        :return: The squared distance
        """

It's a bit pedantic I know, but the mathematical correctness of the statement should be valid.

Cheers

**Comment by viblo** [comment]
Thanks for the report! Reports about mistakes in the docs are always welcome. I have committed a fix.
