### ISSUE TITLE
Memory leak with debug draw on pyglet_util

### ISSUE THREAD

**Issue by baskiton** [viblo/pymunk#176]
I checked on two different machines (Windows 10 and Manjaro), the result is one - an uncontrolled and rapid increase in the amount of memory used. The code matches the examples from the documentation. I tried to use batch - the leak stops, but then the objects are not erased from the screen, drawing tracks on it.
A simple example below should illustrate the issue:

```
import pyglet
import pymunk
import pymunk.pyglet_util

game = pyglet.window.Window(800, 600)
options = pymunk.pyglet_util.DrawOptions()
world = pymunk.Space()
world.gravity = (0, -10)

ball = pymunk.Body(1, 50)
ball_shape = pymunk.Circle(ball, 10)
ball.position = (400, 500)
world.add(ball, ball_shape)

@game.event
def on_draw():
    game.clear()
    world.debug_draw(options)

def update(dt):
    world.step(dt)

if __name__ == '__main__':
    pyglet.clock.schedule_interval(update, 1/60)
    pyglet.app.run()
```

**Comment by viblo** [comment]
Thanksd for the report! Will take a closer look asap

**Comment by viblo** [comment]
Can you give some more info, at least which version of python, pyglet and
pymunk you are using?

**Comment by baskiton** [comment]
Python 3.8.2
pymunk 5.6.0
pyglet 1.5.2

**Comment by viblo** [comment]
Ok. Seems to be a bug (or feature) of pyglet 1.5. I had 1.4 installed, and it worked fine without memory leak. With latest pyglet on the other hand I also saw the rapid memory increase.

**Comment by viblo** [comment]
If you upgrade to latest pyglet the memory usage should be back to normal.

**Comment by baskiton** [comment]
Thanks! Now everything works fine.
