### ISSUE TITLE
Vec2d projection divides by 0

### ISSUE THREAD

**Issue by msis** [viblo/pymunk#177]
In the this line : https://github.com/viblo/pymunk/blob/2e3f85678e970dfb8e81259ad1864b602ebb1b2d/pymunk/vec2d.py#L468 , the projection may divide by 0.

If `other == Vec2d(0,0)`, I think the projection should be `(0, 0)`.

If agreed, I will fix and create a PR.

**Comment by viblo** [comment]
Thanks for the report! I agree, make sense to return zero vector if other is zero.
