### ISSUE TITLE
Spatial Hash Support

### ISSUE THREAD

**Issue by DoAltPlusF4** [viblo/pymunk#179]
I was reading up on how to apply spatial hashing when I discovered that Chipmunk itself actually has an option for spatial hashing instead of the standard axis-aligned bounding box tree.

Source: https://chipmunk-physics.net/release/ChipmunkLatest-Docs/#cpSpace-SpatialHash

Could we get an option to enable this?

**Comment by viblo** [comment]
Hi! Definately, just added it to master. So far quite untested, so would be great if you could try it.

**Comment by viblo** [comment]
Realized I should probably give an example use case also:

```space = pymunk.Space()
dim = 10
count = 1000
space.use_spatial_hash(dim, count)
```

**Comment by DoAltPlusF4** [comment]
Thank you for the quick response and implementation!

**Comment by DoAltPlusF4** [comment]
Ill try it out @viblo. Do I need to clone this repo directly or have you already released it to pypi?

**Comment by viblo** [comment]
Clone the repo is quickest. I can make a release later, maybe with a week
or so.
