### ISSUE TITLE
Typo in tank.py for top-down 2D environment

### ISSUE THREAD

**Issue by simbaforrest** [viblo/pymunk#180]
In [this line](https://github.com/viblo/pymunk/blob/8a7809a2428cd705e3d9582d776fdf0ca037538a/examples/tank.py#L92) of the tank.py example, there is a typo:
> pivot.max_Force = 1000

which should be changed to:
> pivot.max_force = 1000

Otherwise, this PivotJoint based ground friction simulation will not work.

**Comment by viblo** [comment]
Big thanks for the report! Fix committed.
