### ISSUE TITLE
pymunk has no attribute 'Space'

### ISSUE THREAD

**Issue by saamirt** [viblo/pymunk#182]
The line `space = pymunk.Space()` in the sample code on the pymunk site causes this error:

`AttributeError: partially initialized module 'pymunk' has no attribute 'Space' (most likely due to a circular import)`

I'm using Windows 10 and Python 3.8.1 (but i've also tried conda in 3.7.6). I installed pymunk by running `pip install pymunk` (and `conda install -c conda-forge pymunk` for conda). Just pasting and running the sample code causes that error. 

The code for reference:

    import pymunk               # Import pymunk..

    space = pymunk.Space()      # Create a Space which contain the simulation
    space.gravity = 0,-1000     # Set its gravity

    body = pymunk.Body(1,1666)  # Create a Body with mass and moment
    body.position = 50,100      # Set the position of the body

    poly = pymunk.Poly.create_box(body) # Create a box shape and attach to body
    space.add(body, poly)       # Add both body and shape to the simulation

    print_options = pymunk.SpaceDebugDrawOptions() # For easy printing

    while True:                 # Infinite loop simulation
        space.step(0.02)        # Step the simulation one step forward
        space.debug_draw(print_options) # Print the state of the simulation

**Comment by viblo** [comment]
Oh, very strange error!

Can you tell me which OS you use, and what is printed when you do "import
pymunk" ?

**Comment by saamirt** [comment]
I'm using Windows 10. Importing pymunk works fine. Trying to run `from pymunk import Space` causes the same error.

**Comment by viblo** [comment]
Ok, and when you import pymunk is anything printed out?

**Comment by saamirt** [comment]
Just running `import pymunk` by itself prints out:
`Loading chipmunk for Windows (64bit) [C:\Users\[USERNAME]\AppData\Local\Programs\Python\Python38\lib\site packages\pymunk\chipmunk.dll]`

**Comment by viblo** [comment]
Ok. Very strange, can it be something with your environment? I just created a new conda env and installed and ran pymunk there without problem, so should be something special. 

These steps works for me:

    > conda create -n debug
    > conda activate debug
    > conda install -c conda-forge pymunk
    > python
    Python 3.8.3 | packaged by conda-forge | (default, Jun  1 2020, 16:59:10) [MSC v.1916 64 bit (AMD64)] on win32
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import pymunk
    >>> pymunk.Space()
    <pymunk.space.Space object at 0x000001DBD7C81AF0>
    >>> pymunk.version
    '5.6.0'


Some questions:

1. Did you install pymunk previously, or is this the first time?
2. Can you check what files what is actually inside the pymunk package dir (C:\Users\[USERNAME]\AppData\Local\Programs\Python\Python38\lib\site packages\pymunk)? Both when you use a conda env and when you installed directly with pip.
3. Just to double check: What version of Pymunk did you try with?

**Comment by viblo** [comment]
4. Another question: How did you install Python?

**Comment by saamirt** [comment]
Sorry, I don't think the issue was with pymunk. I tried in a seperate location and resolved the issue. Sorry for the trouble, and thank you for your help, @viblo.

**Comment by viblo** [comment]
Great that you managed to solve the problem!

Another user (at least I think you are not the same :)) reported a similar
problem on stackoverflow at
https://stackoverflow.com/questions/62882880/pymunk-verification-test-failing-after-fresh-installation

If you could write something more about how you fixed the problem it would
be great.
