### ISSUE TITLE
setting the body's velocity to (0,0) doesnt actually set its velocity to (0,0)

### ISSUE THREAD

**Issue by NovialRiptide** [viblo/pymunk#185]

**Comment by viblo** [comment]
Thanks for the report!

Can you give a small code example of the problem?

**Comment by NovialRiptide** [comment]
`
class entity:
    def __init__(self, body, size, tps=300, tilemap=None):
        self.tps = tps
        self.tilemap = tilemap

        # animations
        self.tick = 0
        self.current_texture = None
        self.image_offset_position = [0,0]

        # pymunk setup
        self.body = body
        self.width, self.height = size
        self.poly = pymunk.Poly(self.body, [
            (-self.width/2,-self.height/2), (self.width/2,-self.height/2), (self.width/2,self.height/2), (-self.width/2,self.height/2)
        ])

# player entity setup
player_pos = 0,0
body = pymunk.Body(100, 1666)
body.position = player_pos
player = gamedenRE.entity(body, [200*RENDER_SIZE,200*RENDER_SIZE])
player.poly.friction = 1
player.poly.elasticity = 0
space.add(player.body, player.poly)


# game functions
def game_reset():
    execute_data_points(loaded_tilemap, 0)
    space.gravity = 0,0
    player.body.velocity = pymunk.Vec2d(0.0, 0.0)
`

**Comment by viblo** [comment]
Im not sure I can see the issue. What happens and what do you expect to happen?

I made this qiuck test where setting velocity to 0,0 works as expected:
```
import pymunk

space = pymunk.Space()

body = pymunk.Body()
c = pymunk.Circle(body, 10)
c.density = 1
space.add(body, c)

body.velocity = 10,0

space.step(1)
print(f"pos: {body.position}, velocity: {body.velocity}")

space.step(1)
print(f"pos: {body.position}, velocity: {body.velocity}")

body.velocity = 0,0
space.step(1)
print(f"pos: {body.position}, velocity: {body.velocity}")

space.step(1)
print(f"pos: {body.position}, velocity: {body.velocity}")

```

**Comment by NovialRiptide** [comment]
when i set the velocity to `0,0`, it turns into `Vec2d(-4.498482723921359e-07, 1.932500688491376e-06)` instead. are there any other variables that are affecting the body's position?

**Comment by NovialRiptide** [comment]
Nevermind, im just stupid.
