### ISSUE TITLE
Issues with setting Body velocity.

### ISSUE THREAD

**Issue by DoAltPlusF4** [viblo/pymunk#186]
So, I have been using Pymunk for a while now, but have constantly been running into this strange issue:

If I try to set a (dynamic) body's velocity by doing the following, it will seem to be able to clip into objects quite far:
```py
def update(dt):
    body.velocity = TARGET_VELOCITY
```

However, if I set a (dynamic) body's velocity by doing this, it works fine.
```py
def velocity_func(body, gravity, damping, dt):
    body.velocity = TARGET_VELOCITY

body.velocity_func = velocity_func
```

In the image below, the top blue square is using the first method, and the bottom is using the second method. The top square is clipping into the static wall, despite them both using the exact same velocity.
![image](https://user-images.githubusercontent.com/57148878/89193071-57552100-d59d-11ea-96d7-e44209a9be1a.png)

What would you recommend I do for moving an object around? 
I am making a top-down shooter, so I need fairly snappy movement.

**Comment by viblo** [comment]
When Space.step is called it will first update the positions of all objects based on their existing velocities, then check which bodies is colliding and then update the velocities by running the velocity function. So the velocity is updated at different times in the step simulation.

(If you are curious you can check the source at https://github.com/viblo/pymunk/blob/master/chipmunk_src/src/cpSpaceStep.c#L336 )

Anyway, to move something I think you can try either using the velocity function you already found, or to apply a force on the body. Apply impulse is similar to setting the velocity directly, while applying a force is more similar to setting the velocity in the velocity function.
There's a old discussion about the same issue in Chipmunk (Which is the c library Pymunk uses to do the actual physics calculations) here: https://chipmunk-physics.net/forum/viewtopic.php?f=1&t=2447

**Comment by DoAltPlusF4** [comment]
May I ask what `Body.update_velocity(body, gravity, damping, dt)` does then?
If I use the function above I am not doing update velocity because I am overwriting the velocity function, so I would probably need to know what I am skipping out by doing so.

**Comment by DoAltPlusF4** [comment]
It does seem that they mention this in the forum post you linked to
![image](https://user-images.githubusercontent.com/57148878/89217613-626f7780-d5c4-11ea-81f5-db7c247edd3b.png)

**Comment by DoAltPlusF4** [comment]
One last thing, they seem to mention `cpBodySetForce`, but I can't see the Pymunk equivalent in the docs, is there any way to get this kind of behaviour?
![image](https://user-images.githubusercontent.com/57148878/89217813-bc703d00-d5c4-11ea-9f03-19b2ff76ce63.png)

**Comment by viblo** [comment]
There are two functions to apply the force. Check this http://www.pymunk.org/en/latest/pymunk.html#pymunk.Body.apply_force_at_local_point
and this http://www.pymunk.org/en/latest/pymunk.html#pymunk.Body.apply_force_at_world_point

`Body.update_velocity` exists so that you can easily use the existing logic. Either if you want to reset the original velocity function, or if you want to apply some custom logic and then also do the original calculations. Check the documentation for velocity_func for 2 examples for how it can be used: file:///C:/code/gh/viblo/pymunk/docs/html/pymunk.html#pymunk.Body.velocity_func

**Comment by DoAltPlusF4** [comment]
Thanks for the clarification!
