### ISSUE TITLE
How to simulate air resistance with pymunk

### ISSUE THREAD

**Issue by swiftech** [viblo/pymunk#187]
I need to simulate the air resistance like a football kicked off and be slowed down by the air, I didn't find anything about it in the document and anywhere else. Could you consider this case and put some functionalities or workarounds.

**Comment by viblo** [comment]
There is no built in ready to use way to do it, instead you will have to implement it.

One way to do it is shown in the arraows example included in pymunk: https://github.com/viblo/pymunk/blob/master/examples/arrows.py . See also this Q/A on stackoverflow: https://stackoverflow.com/questions/61863480/lift-drag-or-buoyancy-using-pymunk/61908607#61908607
