### ISSUE TITLE
Raspberry Pi Ubuntu ARM 64

### ISSUE THREAD

**Issue by MichaelMarquartBusinessApps** [viblo/pymunk#192]
Can you implement an software switch for Ubuntu ARM 64, the compiler has no option "-m64".
I have remove the lines (see below) in the setup.py file to compile it.

https://github.com/viblo/pymunk/blob/master/setup.py

#if get_arch() == 64 and not platform.machine().startswith('arm'):
#    compiler_preargs += ['-m64']
#elif get_arch() == 32 and not platform.machine().startswith('arm'):
#    compiler_preargs += ['-m32']

Best regards,
;-)

**Comment by viblo** [comment]
Thanks for the report! 
I believe this is the same issue as in this PR https://github.com/viblo/pymunk/pull/190 that was merged (but has not yet been released). I will try to hurry up to make a release so you dont need to hack the setup.py file.

**Comment by viblo** [comment]
I have just released Pymunk 6.0.0. This version should work without troubles (and has even prebuilt wheels for arm64). Would be great if you had the opportunity to test it! (Note however that this version contains several api breaking changes, so if you have existing code you will very likely need to do some adjustments)
