### ISSUE TITLE
ModuleNotFoundError: No module named 'pymunkoptions'

### ISSUE THREAD

**Issue by Lucifer713304** [viblo/pymunk#193]
Traceback (most recent call last):
  File "D:/Pycharm programs/Arcade/Arcade_basic.py", line 1, in <module>
    import arcade
  File "C:\Users\Dr.Kumar\AppData\Local\Programs\Python\Python38-32\lib\site-packages\arcade\__init__.py", line 103, in <module>
    from .drawing_support import calculate_hit_box_points_detailed
  File "C:\Users\Dr.Kumar\AppData\Local\Programs\Python\Python38-32\lib\site-packages\arcade\drawing_support.py", line 7, in <module>
    import pymunkoptions
ModuleNotFoundError: No module named 'pymunkoptions'

This is an error that I'm getting whenever I run my program. Sorry if I'm asking this question in the wrong place, I'm new to github. A little help would be appreciated.

**Comment by viblo** [comment]
This is because the arcade library has not been updated to work with Pymunk 6.0.0 that was released just a day ago. The quickest fix for you would be to downgrade Pymunk to the earlier 5.7 verison. With pip you can do it in this way: `python -m pip install -U pymunk==5.7.0`.

**Comment by viblo** [comment]
There is already a issue report in the arcade github issue tracker for this problem: https://github.com/pythonarcade/arcade/issues/799
When arcade has implemented a fix everything should work out of the box again.

(The 6.0 version of Pymunk contains quite a bit of breaking API changes, so some amount of breakage was expected)
