### ISSUE TITLE
Python 3.10 wheels

### ISSUE THREAD

**Issue by einarf** [viblo/pymunk#203]
Unless I am blind there are no python 3.10 wheels in the latest version on PyPI : https://pypi.org/project/pymunk/6.2.0/#files

People are slowly starting to move over to 3.10 and it would be nice to have this support.

**Comment by viblo** [comment]
Thanks for the reminder, I will put out a 3.10 wheel.

**Comment by viblo** [comment]
Just made a new release, 6.2.1 with more wheels, including 3.10.
