### ISSUE TITLE
How do you make objects draggable?

### ISSUE THREAD

**Issue by nerd-man** [viblo/pymunk#212]
I'm new to pymunk and have seen people make draggable objects before, but I don't know how to do it my self. Can anyone help me do that? Also I am using pygame

**Comment by viblo** [comment]
The base idea is that you create a body that represents the mouse pointer that does not have a shape, and is not added to the space. Then you put a constraint such as a damped spring between it and the target objects body while the object is being dragged. There's an example in the newtons cradle example here: https://github.com/viblo/pymunk/blob/master/examples/newtons_cradle.py

**Comment by nerd-man** [comment]
Thank you, That really helped!
another question. is there a way to make it so the damped spring constraint is invisible?

**Comment by viblo** [comment]
Im guessing you use pymunks built in drawing? If so, you can turn off all constraints drawing by setting the flags on the SpaceDebugDraw object (e.g. if you use pygame that would be the `pymunk.pygame_util.DrawOptions.flags`) as described here: http://www.pymunk.org/en/latest/pymunk.html#pymunk.SpaceDebugDrawOptions.flags

**Comment by nerd-man** [comment]
Thank you! That has been a big help
