### ISSUE TITLE
matplotlib_util_demo.ipynb does not work

### ISSUE THREAD

**Issue by dudung** [viblo/pymunk#225]
As I download and execute [`matplotlib_util_demo.ipynb`](https://github.com/viblo/pymunk/blob/65d2803a/additional_examples/matplotlib_util_demo.ipynb) it produces

```
ModuleNotFoundError                       Traceback (most recent call last)
Input In [1], in <cell line: 4>()
      2 import pymunk
      3 from pymunk.vec2d import Vec2d
----> 4 from shapes_for_draw_demos import fill_space
      5 import pymunk.matplotlib_util

ModuleNotFoundError: No module named 'shapes_for_draw_demos'
```
which I believe it can't find the required file [`shapes_for_draw_demos.py`](https://github.com/viblo/pymunk/blob/7454b216/pymunk/examples/shapes_for_draw_demos.py) which is located in subfolder in other folder.

```
pymunk
+-- additional_examples
|   +-- matplotlib_util_demo.ipynb
+-- pymunk
    +-- examples
        +-- shapes_for_draw_demos.py
```

**Comment by viblo** [comment]
Thanks for the report. Yeah, looks like the import were not updated when I rearranged the folders. I will fix.

**Comment by dudung** [comment]
Dear @viblo, is such a minor correction worth it to open a pull request? Or just open a new issue like this one to report it? Thanks for the answer.

**Comment by viblo** [comment]
Both issue and PRs would be fine. But the most important part is the issue, fixing this small thing is no problem :) 

Anyway, its fixed in master now.
