### ISSUE TITLE
Space.debug_draw for off-screen Circle erroneously draws as full-width streaks

### ISSUE THREAD

**Issue by nrichards** [viblo/pymunk#227]
Issue: 

Using `Space.debug_draw` for `pymunk.Circle` draws the Circle erroneously as a full-screen-width rectangle if it is:
a) off-screen, and 
b) to the left of the viewport

Illustration:

* See code sample - I (biased) think it is fun: [bug_space_draw_ball-offscreen_streak.py.txt](https://github.com/viblo/pymunk/files/11181290/bug_space_draw_ball-offscreen_streak.py.txt)
* One ball (press **SPACE**) that bounced to the left of the large platform
<img width="1251" alt="Screenshot 2023-04-07 at 1 00 57 PM" src="https://user-images.githubusercontent.com/704698/230671816-5ff3396d-5f77-4a67-9d7b-b7136d4d1e8f.png">
* Many balls (hold **SHIFT + SPACE**) which bounced to the left of the platform, as well as several which remain on-screen correctly interacting with the platform, not yet falling off
<img width="1246" alt="Screenshot 2023-04-07 at 1 01 03 PM" src="https://user-images.githubusercontent.com/704698/230671812-f6b63e81-5860-4ddf-b31c-9203584c35d8.png">
* [Video](https://youtu.be/B5FeGrXIpLk)

Discussion:

Thank you again for the fun, accessible Chipmunk2d adaptation. 

I speculate there is an issue in Chipmunk which exposed Circle() shapes are drawn when they are off-screen. I dug a little and did not find low-level drawing inside pymunk, so I concluded it is likely a Chipmunk issue. But this was a shallow investigation, 

This does not occur when the shape is a `Poly.create_box`.

**Comment by viblo** [comment]
Humm.. I am not able to reproduce this, when I run it it behaves as expected. What OS, Python and Pymunk versions do you use?

**Comment by viblo** [comment]
Answering myself: This looks like a pygame bug in pygame 2.3.0. Running pygame 2.2 (or earlier) it works fine.

**Comment by viblo** [comment]
Already found and a fix on the way here: https://github.com/pygame/pygame/issues/3778

**Comment by nrichards** [comment]
Wonderful. Confirmed 2.2 doesn't have the problem - and I am looking forward to pygame 2.4 now! I read and understand the fix in pygame <3.

Thank you Victor for researching this for me ☺️.

**Comment by illume** [comment]
Hey hey. pygame==2.4.0 has a fix in it.

**Comment by nrichards** [comment]
Fixed.

Note the "NO Pink Streaks" in this updated pygame==2.4.0 test-run.

<img width="1312" alt="image" src="https://user-images.githubusercontent.com/704698/235374977-77756d68-0601-436b-bbec-37b3602bab57.png">

Hey hey! Good Sunday to you.

![image width="30"](https://user-images.githubusercontent.com/704698/235374993-ae75a962-9711-4f00-a19c-05ee639ca8cc.png)
