### ISSUE TITLE
Body.copy() raising AttributeError

### ISSUE THREAD

**Issue by GuillaumeBroggi** [viblo/pymunk#236]
In the following situation, `Body.copy()` will raise `AttributeError` . I don't think we should expect this piece of code to work correctly, as it probably doesn't follow good practice. However, the resulting error is rather cryptic, so I decided to report it in case anyone else encounters the same problem.

```python
import pymunk

class MySim:
    def __init__(self) -> None:
        self.space = pymunk.Space()
        self.x =10
        self.y=20

    def position_func(self, body, dt):
        body.position = (self.x, self.y)
        body.update_position(body, dt)

my_sim = MySim()
space = my_sim.space

body = pymunk.Body()
space.add(body)

body.position_func =  my_sim.position_func

body.copy()
```

This code will fail with 
> AttributeError: 'Body' object has no attribute '_space'

This is due to the "circular"  reference (not sure this is the correct wording): the body is added to a space that is an attribute of the `MySim` object, then the `position_function` references the same object.

This code for instance do not produce errors:

```python
import pymunk

class MySim:
    def __init__(self) -> None:
        self.space = pymunk.Space()
        self.x =10
        self.y=20

    def position_func(self, body, dt):
        body.position = (self.x, self.y)
        body.update_position(body, dt)

my_sim = MySim()

space=pymunk.Space()

body = pymunk.Body()
space.add(body)

body.position_func =  my_sim.position_func

body.copy()
```

**Comment by viblo** [comment]
Ah, this was a tricky case. Im not sure its possible to fix the issue.. Maybe body could have a weak ref to the position_func, but on the other hand a user might expect Pymunk to hold a proper reference to it which this would break. And when I just made a quick test it created another pickle error.

As for a better error message I guess I could try. Not super obvious if this can happen for some other strange reason, but I guess I could add an assert. It is a very tricky error, so a better error msg would be very helpful.

**Comment by viblo** [comment]
Did some more investigation and seems its not possible to support this case, at least not without some advanced workaround.. But I added an assert to give a better error message at least.
