### ISSUE TITLE
How to get the net force from a set of collisions 

### ISSUE THREAD

**Issue by rdesc** [viblo/pymunk#244]
Hi, so I think this question might be a little out of scope so feel free to ignore / close the issue but I'm hoping to get your thoughts on a problem I'm having.

So I'm working on a ship-ice simulator (see attached demo video) for a research project and have managed to get some fairly nice physics going (both visually and in terms of the logged collision data) using Pymunk.  

In my current setup the ship is configured as a Kinematic body and I have a dynamics model which takes as input the current ship velocities + the actuator inputs to follow the path and computes the updated ship velocities which I then feed to pymunk. This has worked nicely so far however this means the ship is currently not affected by the forces it experiences from the ship-ice collisions. I'm hoping to possibly extend my simulator to account for this.

My current thinking is I leave the ship as a Pymunk Kinematic body but now somehow incorporate the collision info into my ship dynamics code. Probably what I need is the net force from the set of collisions that occured in a given time step. 

Let me know if you have any thoughts or suggestions. Thank you!

https://github.com/viblo/pymunk/assets/39059473/bd24ca04-3166-4a65-b313-af5dce7762d3

**Comment by viblo** [comment]
Nice video, the simulation looks really cool!

I wonder, now that the ice blocks should affect the ships, wouldn't it be easier (and in some way closer to reality) to just let the ship be a dynamic body and apply a force on it? Otherwise you will calculate the same thing more or less anyway?

But otherwise, I think you can use the each_arbiter callback function to gather up all the collision information. Arbiter has `total_impulse` and `total_ke` which I think can help.
(Maybe this information would be interesting regardless even with the dynamic body, if you want to adjust the force of the ship based on this instead of ship velocity. Also maybe useful to know how heavy the ice blocks hits the ship..?)

**Comment by rdesc** [comment]
Thanks! It took a good amount of tuning and tweaking but I'm quite happy with the result. Your most recent change with the batch module helped sim speed a lot 🚀 

Yea so having the ship be a dynamic body was the other option I was thinking but I'm not sure if this is the right solution since I would like to still use the ship dynamics (its a linear state space model) as part of the sim which computes the thruster RPM, and updated velocities. Maybe this could work if the ship dynamics model gives me the impulses which I then feed to pymunk.

For sure! I'm already logging `total_impulse` and `total_ke` for all the ship-ice collisions that occur for later analysis so I'm familiar with that part of the API. And you're right, collecting the `total_impulse`'s for each of the collisions would be what I need if I go the other way of keeping the body kinematic. 

On another note, I'm considering reporting the contact force from the ship-ice collisions rather than impulses. However, I noticed that the impulse values seem to stay more or less the same when I change the simulation time step (e.g. given the same two bodies colliding at same speed with dt = 0.01 --> impulse = 1000 so force = 100,000 and with dt = 0.1 --> impulse = 1000 so force = 10,000) so I'm unsure whether the contact force values are meaningful here. Thoughts?

**Comment by rdesc** [comment]
I think I may have figured out that last comment after reading more about impulse based physics engines https://hmbd.wordpress.com/2021/10/24/a-short-primer-on-impulse-based-dynamics/ 

Seems like the point isn't to try to accurately compute the forces but instead to stick with the much-easier-to-deal-with impulses.

I'll close this issue for now, but happy to hear if you have any other comments/suggestions.

**Comment by viblo** [comment]
Not sure I was of any help, but great that you found a path forward regardless :)

**Comment by rdesc** [comment]
Hey @viblo just wanted to share the final result of the project I was working on :)
- Preprint https://arxiv.org/abs/2411.17155
- Git repo https://github.com/rdesc/AUTO-IceNav

It would be great to include this project as part of your showcase.

Thanks again for your work on pymunk!

**Comment by rdesc** [comment]
Thank you! 

I'd say 2/3 of the 60 hours was spent inside pymunk and then 1/3 in my planning code. I never properly tested this though so hard to say. I do know however that the simulator does slow down quite a bit the more ice pieces (max I think was ~1500) there are to simulate which makes sense. Note, in simulation time its around 200 hours thats simulated so much faster than real-time which is nice.
