### ISSUE TITLE
How is ContactPoint.distance calculated?

### ISSUE THREAD

**Issue by Python-ZZY** [viblo/pymunk#253]
Hi! I can't understand what distance does ContactPoint.distance mean? I know it seems to represent the distance between ContactPoint.point_a and point_b, but I don't understand how these two points are calculated. Could you give me some help?

**Comment by viblo** [comment]
Humm.. Have you seen the contact point example here: http://www.pymunk.org/en/latest/examples.html#collisions-py ?

**Comment by Python-ZZY** [comment]
I've seen it, but I don't quite understand how the point of contact is chosen by pymunk.

**Comment by viblo** [comment]
Im not sure exactly what you are after, but if its deep into the technical part, then there's a overview of the algorithms used on the creator's of Chipmunk company website here https://web.archive.org/web/20230327132329/http://howlingmoonsoftware.com/wordpress/enhanced-collision-algorithms-for-chipmunk-6-2/ (the non-archive version seems to be down). 

For even more technical deep dive, the implementation itself is in cpCollision: https://github.com/viblo/Chipmunk2D/blob/master/src/cpCollision.c#L350

To better understand the GJK  algorithm I think this article is quite helpful: https://computerwebsite.net/writing/gjk

**Comment by Python-ZZY** [comment]
That's exactly what I need. Thank you!
