### ISSUE TITLE
how to check for collisions on objects that have not been added

### ISSUE THREAD

**Issue by Notenlish** [viblo/pymunk#256]
I have a small pygame demo with pymunk that allows th user to spawn in different blocks. However, if the user spawns the block inside another block the physics gets kinda messy. is it possible to check if an object that hasnt been spawned will collide with any other objects?

**Comment by aatle** [comment]
Hi, this is kind of late, but the best way to do this is [`Space.shape_query()`](https://www.pymunk.org/en/latest/pymunk.html#pymunk.Space.shape_query) method, which can take shapes that have not been added (though they need to be attached to a body to have a position).
Alternatively, one could use a sensor shape, which makes it uncollidable but still able to detect collisions.

**Comment by Notenlish** [comment]
Oh I see, thanks. Late reply isn't a problem, I'm relieved to finally know how to fix it. Thanks a lot!
