### ISSUE TITLE
Method to create `Vec2d` from magnitude and angle

### ISSUE THREAD

**Issue by aatle** [viblo/pymunk#261]
Often, I am given a magnitude and an angle in radians, and I need to create a vector from this.
The current ways to do it:
```py
Vec2d(magnitude, 0.0).rotated(angle)
Vec2d(cos(angle), sin(angle)) * magnitude
```
It would be nice to have a classmethod that can do this more cleanly:
```py
@classmethod
def from_polar(cls, r, theta):
    return cls(cos(theta) * r, sin(theta) * r)

Vec2d.from_polar(magnitude, angle)
```
I count 6 possible places I could use this in my codebase.
Example:
Apply an impulse of *x* magnitude, at an angle pointing towards the mouse cursor.

**Comment by viblo** [comment]
Sounds reasonable. I did a quick check and both pygame and pyglet has such a method on their vector classes. 
Something like this
```
    @staticmethod
    def from_polar(length, angle) -> "Vec2d":
        """Create a new Vec2d from a length and an angle (in radians)

        >>> Vec2d.from_polar(2, 0)
        Vec2d(2, 0)
        >>> pymunk.Vec2d(2, 0).rotated(0.5) == Vec2d.from_polar(2, 0.5)
        True 
        """
        return Vec2d(cos(angle) * length, sin(angle) * length)
```
(staticmethod since the other ones are also static, and length/angle as names since that is the names already used in other vec2d methods)

**Comment by viblo** [comment]
Thanks for this, next release of pymunk will contain a from_polars method :)
