### ISSUE TITLE
About installing Wasm wheel (6.9.0) with PyScript (Pyodide)

### ISSUE THREAD

**Issue by Kazuhito00** [viblo/pymunk#265]
Hello. Thank you for your great work.

[Releases: 6.9.0](https://github.com/viblo/pymunk/releases/tag/6.9.0)  I would like to ask a question about micropip install of Wasm wheel's pymunk-6.9.0-cp312-cp312-pyodide_2024_0_wasm32.whl on PyScript.

When I try to install this whl on PyScript, the following error occurs.
"Error installing Pymunk: Requested 'cffi>=1.17.1', but cffi==1.16.0 is already installed"

Pyodide's cffi seems to be [1.16.0](https://pyodide.org/en/stable/usage/packages-in-pyodide.html), but what are the steps to install Pymunk?
Do I need to build and install cffi?

---

The source code I tried is below.
```python
try:
    import micropip

    print("micropip successfully imported")
except ImportError as e:
    print(f"Error importing micropip: {e}")

try:
    await micropip.install("pymunk-6.9.0-cp312-cp312-pyodide_2024_0_wasm32.whl")
    print("Pymunk installed successfully")
except Exception as e:
    print(f"Error installing Pymunk: {e}")

try:
    import pymunk

    print("Pymunk successfully imported")
except ImportError as e:
    print(f"Error importing Pymunk: {e}")
```
[src.zip](https://github.com/user-attachments/files/18140847/src.zip)

**Comment by viblo** [comment]
Thanks for the report!

Oh, nice find. Earlier versions of Cffi is not compatible with the latest
setuptools which is why Pymunk requires >17.1.x.  I will have to
investigate a bit, maybe the cffi version from pyodide can be updated (or I
can relax the requirement for pyodide specifically).

Btw, you are the first person who have reported using the podide wheels.
Can I ask how you use it?

**Comment by viblo** [comment]
Created a PR against pyodide to update their dependency on CFFI here: https://github.com/pyodide/pyodide/pull/5261

**Comment by Kazuhito00** [comment]
Thank you for your detailed explanation and response.

> Btw, since you are the first person who have reported using the podide wheels,
can I ask how you use it?

I would like to create a 2D game by combining pygame-ce, Pyxel, and Pymunk.
I wanted to publish the game I created in a browser, and was considering PyScript.

**Comment by viblo** [comment]
I just relaxed the cffi requirement when building/installing pymunk for pyodide, and made it run the tests also when building for pyodide to so this kind of easy issues can be avoided in the future. This will be included in the next Pymunk version. (Not sure yet when it will be released). 
Thanks again for the report!

**Comment by viblo** [comment]
New Pymunk (6.10.0) released which fixes this issue. (Guess it will take a while for Pyodide to release)

**Comment by Kazuhito00** [comment]
Thank you for releasing it.
I immediately tried it in combination with Pyxel. It's working fine.

https://kazuhito00.github.io/pyxel-pymunk-web-test/

![image](https://github.com/user-attachments/assets/42f9979a-564c-49a0-967e-6ee1e80d5f8d)

**Comment by viblo** [comment]
Nice!
