### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'README.rst'

### ISSUE THREAD

**Issue by cjbates-mit** [viblo/pymunk#81]
Hi,
I'm running Windows 7 x64, and I get the above error after running setup.py. Which README.srt is it pointing to? Because the file is definitely in the same directory as setup.py. 
Previously, I tried the .exe install for windows 64, but it failed. As far as I could tell, it didn't copy all the necessary folders. Ideas?

**Comment by viblo** [comment]
The new release Pymunk 5.0 should work fine under 64bit python on windows.
