### ISSUE TITLE
pymunk and chipmunk64.dll issue drawing Segments

### ISSUE THREAD

**Issue by romarro** [viblo/pymunk#89]
I am working from a Win64 bit.
I have just get the pymunk from github, compiled with mingw32 compiler the chipmunk, and installed on my 2.7 winpython distribution.
The problem I have is that the segment doen't draw correctly
here is an example of the balls_and_lines.py
Trying to draw a line:
![issue](https://cloud.githubusercontent.com/assets/7783693/4873261/ccf94b84-6208-11e4-8c58-1c4b08563861.png)
and after that the line begins from 0.0 
![issue1](https://cloud.githubusercontent.com/assets/7783693/4873264/e5a7c43a-6208-11e4-975f-51113f8e7527.png

As I saw the 
shape= pm.Segment(body, line_point1, line_point2, 0.0) takes into account only the line_point1 and the line_point2 it is ignored. 

Can you help with this?

**Comment by zcv** [comment]
Needing to use 64 bit here, your temporary fix creating Segments worked for me, but I think I might have a similar issue in creating a poly, for example from pyramidDemo.py
points = [(-size, -size), (-size, size), (size,size), (size, -size)]
shape = pymunk.Poly(body, points, (0,0))

**Comment by viblo** [comment]
Yes, unfortunately there has been no progress on #27 and py 64bit compatibility on windows. Right now Ive started to update pymunk to use Chipmunk 7. When done I will take a look at the 64bit issue again, hopefully things are easier with the latest version.

**Comment by viblo** [comment]
Should be fixed now with pymunk 5.0
