### ISSUE TITLE
py3 incompatibility in pymunk/__init__

### ISSUE THREAD

**Issue by estevaofon** [viblo/pymunk#91]
Hello,
When I try to run pymunk/examples/playground.py in python 3 it raises the following issue:
![issue](https://cloud.githubusercontent.com/assets/7939043/5598521/cbd94506-9296-11e4-9464-7416cc740a33.png)
I've tried to fix this incompatibility in "__init__.py" this way:
verts = (Vec2d * len(list(vertices))) 
but it raises other errors.
Using python 2 the playground.py works fine.

**Comment by viblo** [comment]
Thanks for the report. I will take a look as soon as I have a lite time over (just came back from a 2 week vacation)

**Comment by estevaofon** [comment]
I'm glad to help. Your project is awesome!
