### ISSUE TITLE
Update to Chipmunk 7.0

### ISSUE THREAD

**Issue by viblo** [viblo/pymunk#92]

**Comment by pradyun** [comment]
Just came by to say: :+1:

**Comment by viblo** [comment]
I think they separate. But ill take a look at it once pymunk is updated with chipmunk 7. (I think Im about half way done with the core features atm)

**Comment by pradyun** [comment]
> I think they separate.

Oh, Ok!

> I think Im about half way done with the code feature atm

Great!

---
I'm waiting for this update! Well, I'm not holding my breath or anything...

PS: If you need extra hands on deck, I'll be happy to help, (if I can)!

**Comment by viblo** [comment]
the newly relaesed pymunk 5.0 uses chipmunk 7.

**Comment by pradyunsg** [comment]
Yay!!! Thanks!
