### ISSUE TITLE
python 3 issue with sort(cmp=...)

### ISSUE THREAD

**Issue by vpribish** [viblo/pymunk#96]
my error was : 
> File ".../python3.4/site-packages/pymunk/util.py", line 153, in convex_hull
>    points.sort(cmp = f)
> TypeError: 'cmp' is an invalid keyword argument for this function

this is no longer valid in python 3 -you need to use the `key` argument instead - but i'm not sure how to do that given what's happening in this comparison function.

here's a hack  : import cpm_to_key from functools and then change the line to : 
`    points.sort(key = cmp_to_key(f))`

**Comment by viblo** [comment]
Good catch, thanks for the report!
I have added a fix to the chipmunk7 branch. I dont plan to do any more releases of pymunk 4 (the upcoming chipmunk 7 will be pymunk 5.x I think). Hopefully its ok for you to use the hack you already found until I have the next version of pymunk ready for use.

**Comment by viblo** [comment]
Should be fixed now with pymunk 5.0
