### ISSUE TITLE
Add link to youtube tutorial(s)?

### ISSUE THREAD

**Issue by viblo** [viblo/pymunk#98]
Saw this pymunk tutorial on youtube: https://www.youtube.com/watch?v=3JraKrgfu_U  Might be nice to put a link to it from the external tutorials page.

**Comment by totex** [comment]
Hi viblo, i also started to create pymunk tutorial videos. If you want you can put them on the external tutorials page. Here is a the link to the playlist: https://www.youtube.com/watch?v=pRk---rdrbo&list=PL1P11yPQAo7pH9SWZtWdmmLumbp_r19Hs

**Comment by viblo** [comment]
Looks like you have created a very good set of tutorials! I only very quickly looked at them so far, and they look very nice. I will make sure to add them to the docs/webpage either tonight or maybe during weekend.
